### ISSUE TITLE
login geht nicht wenn https und authentifizierung an

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.web#10]
ich kann mich nicht gegen das System authentifizieren .. es werden zwar user psw abgefragt aber nicht erkannt .. es wird immer nur der Admin agezeigt...

im vis 2 widgets der eine ist mit Sichtbarkeit für Admin der andere Benutzer.. 
ich sehe nur den Admin obwohl der Benutzer angemeldet ist

**Comment by GermanBluefox** [comment]
Sollte jetzt gehen

**Comment by arteck** [comment]
works fine
