### ISSUE TITLE
letsencrypt cert renewal tries although it is disabled

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.web#101]
web 3.3.0
js-controller 3.2.16
nodejs 12.21.0

web instance tries to renewal my LE cert after 1 month, although this feature is disabled in the settings. Port 80 is only open for iobroker every 3 months when I manually renewal the LE cert. Otherwise this port is used for other device. So, it is sensless to try it every hour already after first month of creation.

> web.0	2021-04-04 09:47:01.846	error	(2308) [LE] {"code":"E_FAIL_DRY_CHALLENGE","context":"cert_renewal","subject":"mydomain.tld","altnames":["mydomain.tld"]}

**Comment by Apollon77** [comment]
Can you please recreate that issue in js-controlelr repo? I can not transfer it

**Comment by Diginix** [comment]
@foxriver76 

Heute mal mit gepatchten JS-Controller 3.2, also mit den LE Anpassungen aus 3.3, und dem web Adapter 3.4.1 das LE Cert verlängert. Hat auch funktioniert aber im Log landen Fehler mit "INVALID_HOSTNAME". Dieser ist aber in der Admin Instanz korrekt hinterlegt. Sonst würde ja auch das Cert nicht passen. Der echte Hostname ist hier im Zitat ersetzt durch "meinedomain.com".

> 2021-05-03 18:06:15.711 - info: web.0 (412234) starting. Version 3.4.1 in /opt/iobroker/node_modules/iobroker.web, node: v12.22.1, js-controller: 3.2.16
> 2021-05-03 18:06:15.977 - debug: web.0 (412234) Adding to Greenlock: meinedomain.com with alternative names meinedomain.com
> 2021-05-03 18:06:16.030 - info: web.0 (412234) Challenge server listening on port 80
> 2021-05-03 18:06:16.030 - info: web.0 (412234) If something is not working and your adapter is not reachable anymore you can turn off HTTPS with executing "iobroker web.0 set --secure false" in your shell.
> 2021-05-03 18:06:16.031 - debug: web.0 (412234) Activating IOSocket
> 2021-05-03 18:06:16.077 - info: web.0 (412234) Secure socket.io server listening on port 443
> 2021-05-03 18:06:16.077 - debug: web.0 (412234) Activating extensions
> 2021-05-03 18:06:16.077 - debug: web.0 (412234) Activating web files from objectDB
> 2021-05-03 18:06:16.097 - info: web.0 (412234) https server listening on port 443
> 2021-05-03 18:06:26.209 - error: web.0 (412234) [LE] {"code":"INVALID_HOSTNAME","context":"add"}
> 2021-05-03 18:06:26.230 - error: web.0 (412234) [LE] {"code":"INVALID_HOSTNAME","context":"add"}
