### ISSUE TITLE
Transport Encryption: allow certificates on local filesystem

### ISSUE THREAD

**Issue by StephanTexxpro** [ioBroker/ioBroker.web#102]
I've tried to enable transport layer encryption (https) in the web adapter's settings. However it seems, that I can only select those certificates which were copied in plain in the system adapter (defaultPrivate and defaultPublic in a vanilla install).

The system adapter also allows to enter the path of a certificate within the filesystem. This is useful, when e.g. letsencrypt certificates are managed (especially renewed) outside the iobroker ecosystem on a superior level. 

Would be great, if the web adapter could make use of those linked certificates as well.

BTW - for sure it would be possible to copy the content of the certificate files directly in the system adapter, however this would require a manual update process (copy & paste) each 90 days after renewal of the letsencrypt certificates.

**Comment by Apollon77** [comment]
This is already implemented. just create certificates in Admin like the "defaultprivate" but enter a local filesystem path instead of a certificate string as content. Then this file is used.

make sure the iobroker user can access the file

**Comment by StephanTexxpro** [comment]
Thanks for the feedback!

I guess I did as described by you, however I cannot select the local certificates. There is also no problem with access rights (as ioBroker runs as root atm).

Please see screenshots attached.

![2021-04-09 08_47_04-intro clean - ioBroker](https://user-images.githubusercontent.com/25078059/114140960-40778300-9911-11eb-8a40-a82e04fbdcda.png)
![2021-04-09 08_47_51-instances - ioBroker](https://user-images.githubusercontent.com/25078059/114140983-4c634500-9911-11eb-8168-ba28a766ad96.png)

**Comment by Apollon77** [comment]
Try restarting admin please or web or iobroker .. might be some thing caches cert list ...

**Comment by StephanTexxpro** [comment]
Nope... still not there. Also deleted the default certs, now the web adapter dropdown only shows 'keins' (guess 'none').

**Comment by Apollon77** [comment]
Do you have spaces in the cert name? try to remove them please

**Comment by StephanTexxpro** [comment]
OK, removed the points from the filenames and spaces and points from the nice names, still no success. Please see attached screenshots.
![2021-04-10 11_00_06-instances - ioBroker](https://user-images.githubusercontent.com/25078059/114264638-57d76e80-99ec-11eb-9e70-bae0d3615425.png)

![2021-04-10 11_00_58-instances - ioBroker](https://user-images.githubusercontent.com/25078059/114264631-4d1cd980-99ec-11eb-9fc5-ced97aeab26b.png)

![2021-04-10 10_59_32-adapters - ioBroker](https://user-images.githubusercontent.com/25078059/114264643-602fa980-99ec-11eb-9373-5692d8beed65.png)

**Comment by GermanBluefox** [comment]
Fixed in 3.4.1
