### ISSUE TITLE
Missing Titel (Admin 5.0.11)

### ISSUE THREAD

**Issue by skvarel** [ioBroker/ioBroker.web#107]
Old UI
![grafik](https://user-images.githubusercontent.com/1114419/116593869-dbb4b480-a921-11eb-823a-c856a7b436fa.png)

React UI
![grafik](https://user-images.githubusercontent.com/1114419/116594003-09016280-a922-11eb-8a5e-199ca88b1b1b.png)

**Comment by Apollon77** [comment]
Will be fixed with js.controller 3.3 comitng to latest right now
