### ISSUE TITLE
Keine Verbindung iobroker.pro

### ISSUE THREAD

**Issue by fuchs-1978** [ioBroker/ioBroker.web#128]
Ich habe den Adapter von 3.4.1 auf 3.4.3. geupdatet. Mit der neuen Version kann ich nicht mehr über den Cloudzugang iobroker.pro auf mein System zugreifen. Es kommt folgende Fehlermeldung im Browser:

Antwort von Ihrem ioBroker kann nicht analysiert werden

Ein Downgrade auf 3.4.1 behebt den Fehler.

Es wurde zweimal getestet, jeweils gleiches Ergebnis.

**Comment by Apollon77** [comment]
Was strht im ioBroker Log mit der neuen Version?

**Comment by fuchs-1978** [comment]
Ich habe dazu keinen Eintrag gefunden, der auf einen Fehler hindeutet

**Comment by Apollon77** [comment]
Irgendwas in der Browser Konsole als Fehler? Bitte mal Screenshots zeigen

**Comment by winnyschuster** [comment]
könnte evtl. mit #129 zusammenhängen.

**Comment by Apollon77** [comment]
sehr wahrscheinlich

**Comment by Apollon77** [comment]
Please check 3.4.4 - 3.4.4 is on npm now, in repo tomorrow morning should fix that
