### ISSUE TITLE
V3.4.3: WEB Server meldet Fehler: index.html not found

### ISSUE THREAD

**Issue by winnyschuster** [ioBroker/ioBroker.web#129]
**Describe the bug**  
WEB Server meldet Fehler wegen fehlender Dateien

Bei aufruf von iobroker_ip:8082 erscheint folgender Fehler:
```/opt/iobroker/node_modules/iobroker.web/www/index.html was not found or no access!```

tatsächlich fehlen in /opt/iobroker/node_modules/iobroker.web/ die Ordner www und src im Vergleich zur 3.4.2. Ein Downgrade behebt den Fehler und die beiden Ordner sind wieder da

**Comment by MK-66** [comment]
Bei mir der genau der gleiche Fehler bei V3.4.3

**Comment by Jogi2020** [comment]
Ich habe das gleiche Problem bei V3.4.
/opt/iobroker/node_modules/iobroker.web/www/index.html was not found or no access!

**Comment by Apollon77** [comment]
Strange ... we check

**Comment by Diginix** [comment]
Bei mir auch bei der Instanz die ein Login verlangt. Die zweite Instanz ohne Login funktioniert weiterhin.

> Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.web/www/login/index.html'
>     at Object.openSync (fs.js:462:3)
>     at Object.readFileSync (fs.js:364:35)
>     at prepareLoginTemplate (/opt/iobroker/node_modules/iobroker.web/main.js:804:25)
>     at /opt/iobroker/node_modules/iobroker.web/main.js:1423:46
>     at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:317:13)
>     at /opt/iobroker/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:335:12)
>     at next (/opt/iobroker/node_modules/express/lib/router/index.js:275:10)
>     at /opt/iobroker/node_modules/iobroker.web/main.js:1128:28
>     at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:317:13)
>     at /opt/iobroker/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:335:12)
>     at next (/opt/iobroker/node_modules/express/lib/router/index.js:275:10)
>     at /opt/iobroker/node_modules/connect-flash/lib/flash.js:21:5

**Comment by Apollon77** [comment]
yes, somehow the www folder was not published ...

**Comment by Apollon77** [comment]
3.4.4 is on npm now, in repo tomorrow morning should fix that

**Comment by winnyschuster** [comment]
@Apollon77 Danke für den Fix!
