### ISSUE TITLE
Warn mit JS-Controller 3.3.14

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.web#130]
Mit JS-Controller 3.3.14 und Web 3.4.4
treten Warn-Meldungen auf.

`
web.0 | 2021-07-07 23:42:22.948 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "88"
web.0 | 2021-07-07 23:42:22.277 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "87"
web.0 | 2021-07-07 23:42:20.950 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "86"
web.0 | 2021-07-07 23:42:20.284 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "85"
web.0 | 2021-07-07 23:42:18.946 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "84"
web.0 | 2021-07-07 23:42:18.274 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "83"
web.0 | 2021-07-07 23:42:16.946 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "82"
web.0 | 2021-07-07 23:42:15.953 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "81"
web.0 | 2021-07-07 23:42:14.947 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "80"
web.0 | 2021-07-07 23:42:13.305 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "78"
web.0 | 2021-07-07 23:42:12.304 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "77"
web.0 | 2021-07-07 23:42:11.312 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "76"
web.0 | 2021-07-07 23:42:10.311 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "75"
web.0 | 2021-07-07 23:42:09.305 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "74"
web.0 | 2021-07-07 23:42:08.304 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "73"
web.0 | 2021-07-07 23:42:07.305 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "72"
web.0 | 2021-07-07 23:42:06.304 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "71"
web.0 | 2021-07-07 23:42:05.312 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "70"
web.0 | 2021-07-07 23:42:04.305 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "69"
web.0 | 2021-07-07 23:42:02.706 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "67"
web.0 | 2021-07-07 23:42:01.706 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "66"
web.0 | 2021-07-07 23:42:00.749 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "65"
web.0 | 2021-07-07 23:41:59.701 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "64"
web.0 | 2021-07-07 23:41:58.766 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "63"
web.0 | 2021-07-07 23:41:57.769 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "62"
web.0 | 2021-07-07 23:41:21.707 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "141"
`

**Comment by Apollon77** [comment]
Hm ... IF thsi erros really come from web adaoter then please find out which of your visualizations are writing the value, becaue it needs to be something like this,
