### ISSUE TITLE
3.4.4 Update lädt Oberfläche Einstellungen nicht

### ISSUE THREAD

**Issue by rmp63526** [ioBroker/ioBroker.web#132]
Hallo, habe eben auf 3.4.4 aktualisiert und seit dem lädt die Oberfläche des WEB.Adapter nicht mehr,
bzw. zeigt mir keine Einstellungmöglichkeiten mehr.
Unter den Reiter "EXTRA" werden mir jedoch die Einstellungsmöglichkeiten angezeigt.

Im Log werden mir keine Fehler angezeigt bis auf  (2071) State "nothing_selected" has no existing object, this might lead to an error in future versions.

Was habe ich bisher versucht:
- System reboot
- Wieder zurück auf 3.4.3 

**Versions:**  
 - Adapter version: 3.4.3
 - JS-Controller version: 3.2.16 
 - Node version: 14.17.1
 - Operating system: Raspberry pi

![Unbenannt](https://user-images.githubusercontent.com/65367883/126306933-85320634-5636-4f94-9fac-b65f2837a187.PNG)

**Comment by Apollon77** [comment]
Bitte gehe mal auf Admin5. geht es da?

**Comment by rmp63526** [comment]
Auf meinem Produktivsystem würde ich ungern den neuen Admin.5 Adapter installieren.
Habe für testzwecke den Admin.5 auf einem anderen Pi laufen und dort funktioniert es.

**Comment by Apollon77** [comment]
ok, ich habe stable zurück auf die 3.4.1. gestellt. bitte downgraden! die 3.4.4 kommt dann erst zusammen mit admin5

**Comment by KoMa1978** [comment]
Gleiches Problem bei mir ... der Downgrade auf 3.4.1 hat geholfen.

Vielen Dank
