### ISSUE TITLE
ACK-Flag issue

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.web#133]
Web Adapter Version 3.4.5

`
<html>
<body>

web.0 | 2021-07-22 16:36:43.792 | warn | (3380) Read-only state "spotify-premium.0.player.device.volume" has been written without ack-flag with value "36"
-- | -- | -- | --
web.0 | 2021-07-22 16:36:41.359 | warn | (3380) Read-only state "spotify-premium.0.player.device.volume" has been written without ack-flag with value "31"

</body>
</html>`

**Comment by Apollon77** [comment]
No, this is no web issue ... find out which visualization you use to set this value and fix there
