### ISSUE TITLE
warning if special binding „local_*“ in vis is used

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.web#137]
**Describe the bug**  
if special binding `local_*` in [vis ](https://github.com/ioBroker/ioBroker.vis#special-bindings) is used follwowing warn-message appears:

`2021-08-27 23:03:52.971 - warn: web.0 (319) State "10" has no existing object, this might lead to an error in future versions `
` 2021-08-27 23:03:55.796 - warn: web.0 (319) State "10" has no existing object, this might lead to an error in future versions`

**To Reproduce**  
- add `{local_navigation}` in a vis- Widget -> `Allgemein `-> `Object ID`

**Expected behavior**  
- no error message if special binding `local_*` is used

**Versions:**  
 - Adapter version: web v.3.4.7 / vis v.1.4.3
 - JS-Controller version: v3.3.15
 - Node version: v12.22.5
 - Operating system: linux

**Comment by Apollon77** [comment]
@ice987987 Bitte das Issue bei vis bzw dem WWidget set anlegen!!
