### ISSUE TITLE
Warn-Message: State "web.0.info.connection"

### ISSUE THREAD

**Issue by Berchemer** [ioBroker/ioBroker.web#147]
v3.4.9

after update, with start of adapter the follwowing warning is shown:

State "web.0.info.connection" has no existing object, this might lead to an error in future versions

**Comment by Cabohne** [comment]
Would it be possible to release a new stable version 3.4.12 or even 3.4.13? The current stable version is still 3.4.9 which shows the above mentioned warning.

**Comment by Apollon77** [comment]
Yes, stable update will come as soon as enough data exists for the latest version

**Comment by Malz1902** [comment]
Yesterday i updated to Version v3.4.9

Now Warn:
State "web.1.info.connection" has no existing object, this might lead to an error in future versions
