### ISSUE TITLE
VPN connection to VIS extremely slow after updating Web Adapter to 3.4.13 and socket.io Adapter to 3.1.5

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.web#148]
Nach einem Update des Web Server Adapters auf V3.4.13 bzw. dem damit verbundenen socket.io Update auf V3.1.5 ist eine VPN Verbindung meines Android Galaxy S20 Handys zur VIS runtime oder auch zu VIS edit extrem langsam geworden (Mobilfunk VPN Verbindung über eine Fritzbox 7590 ins heimische Netz),

Nach der Meldung auf dem Handy „loading values…“ dauerst es ca. 12-15s bis VIS dann endlich mal geladen wird. Den Web Server Adapter habe ich dann zum Test auf debug gestellt und im Log nur gesehen, dass nach dem zweiten Eintrag im Log „web.0 Request authenticate [system.user.admin]“ es ca. 12s dauert bis dann angefangen wird Teile der VIS zu laden, Fehler sind im Log keine zu sehen. Vor dem Update dauerte es an dieser Stelle nur ca. 1-2s.

Leider hilft nach besagtem Update auch kein Downgrade des socket.io Adapters auf die zuvor funktionierende V3.1.4 und des Web Adapters auf V3.4.9 mehr, wenn man einmal das Update auf die o.g. Versionen durchgeführt hatte. Es hilft dann nur noch die VM per Snapshot (VM Debian Buster Proxmox) komplett auf den vorherigen Stand zurückzusetzen. Danach hat man dann wieder die genannten und gewohnten kurzen Ladezeiten.

Gleiches Verhalten bei einem Raspberry Pi4 (mein zweites System). Auch hier ist nach einem Update des socket.io Adapters auf V3.1.5 die extrem langsame VPN Verbindung zur VIS zu beobachten, Auch hier hilft leider nur noch ein vollständiges Zurückspielen des gesamten Raspberry mittels eines vorherigen Images. Downgrade der Adapter oder ein Backup zurückzuspielen reicht dabei leider nicht.

Es scheint möglicherweise ein Problem des socket.io Adapters zu sein, der dieses Verhalten auslöst. Ich weiß leider nicht ob bei einem Update evtl. irgendetwas im js-controller verändert wird, sodass ein Downgrade der Adapter auf die vorherigen Versionen eine Verbesserung daher nicht wieder zurück bringt.

Im heimischen WLAN / LAN (ohne VPN Verbindung über Mobilfunk) ist das Laden der VIS wie gewohnt schnell, sodass mir das Problem zunächst gar nicht aufgefallen ist. Im Übrigen ist eine Verbindung zur Admin Oberfläche über VPN von dem langsamen Laden nicht betroffen, es betrifft wie gesagt nur VIS runtime oder VIS edit.

Meine beiden Systeme (Raspi-Pi4, Proxmox Debian Buster VM) sind vollständig aktuell (beta repository), nodejs V12.22.7, die Mobilfunk VPN Verbindung zur Fritzbox 7590 erfolgt über schnelles LTE (Telekom).
 
Ich hoffe die klasse Entwickler von ioBroker können mein Problem nachvollziehen und ggf. eine Lösung finden. Sorry, dass ich dieses Issue in Deutsch erstellt habe, eine Übersetzung erschien mir dann doch etwas zu kompliziert.

**Comment by MK-66** [comment]
@ Apollon
Ich habe jetzt auf meinem Handy mittels Data Counter Widget App mal geschaut wieviel mobiles Datenvolumen beim Aufruf der VIS über FritzBox VPN bei der neuen socket.io V3.1.5 und web.0 V3.4.13 im Vergleich zu den Vorgängerversionen socket.io V3.1.4 und Web.0 V3.4.9 verbraucht wird:

Mit der neuen Version werden beim Aufruf ca. 18 MB an mobilen Daten verbraucht, während es bei der alten Version nur ca. 1,2 MB sind.

Das erklärt natürlich warum der Aufruf der VIS über VPN so extrem lange dauert. Nur warum werden seit dem Update so viel mobile Daten verbraucht, wird hier irgendetwas mehrfach geladen?

Zur weiteren Info: Mein VIS Projekt ist als zip Export ca. 23 MB groß. Zum Test hatte ich mal eine weitere Proxmox VM (Klon) erstellt mit absolut identischen VIS Projekt, sodass ich den Verbrauch der mobilen Daten zwischen zwei identischen Systemen vergleichen konnte, einmal mit dem neuesten socket.io / web.0 Update und einmal mit den genannten Vorgängerversionen.

Dieser hohe Verbrauch an mobilen Daten ist beim Aufruf über das Handy mittels Samsung Browser und mittels Google Browser im Übrigen gleich, der Browser spielt also keine Rolle.

Vielleicht hilft Dir diese Erkenntnis den Fehler mit der langsamen VPN Verbindung irgendwie einzugrenzen und eine Lösung für das Problem zu finden.

Ein schönes WE wünsche ich Dir.

**Comment by Apollon77** [comment]
Und sicher das du an deiner Vis selbst nicht was geändert hast ?

**Comment by MK-66** [comment]
Ganz sicher sogar, es ist exakt die gleiche VIS und daran wurde nichts vor dem Update von socket.io geändert. Wie gesagt, das Verhalten tritt erst auf sobald ich ein Update von socket.io und web mache. Ich meine sogar, dass das schon beim reinen Update von socket.io passiert unabhängig vom web.0 update. Das kann ich aber gerne in einer einer Proxmox Test-VM nochmal nachstellen, wenn das hilft?

**Comment by MK-66** [comment]
Gerade getestet: Proxmox VM Klon erstellt, socket.io ist im Klon noch auf 3.1.4, web.0 auf 3.4.9, Ladezeit der VIS ca. 2s, mobiler Datenverbrauch über VPN ca. 1MB.

Update socket.io auf 3.1.5 gemacht, web.0 nicht geupdatet (der bekannte info.connection web.0 Fehler taucht im Log auf), Ladezeit der VIS nach dem socket.io update ca. 12s, mobiler Datenverbrauch ca. 18MB.

Ich weiß auch nicht woran das bei mir liegen könnte. Ich nutze in der VIS noch viele eigene DP die unter javascript statt userdata liegen. Könnte es sein, dass sich das socket.io update damit nicht verträgt? 

Auch nutze ich an manchen Stellen in der VIS material design widgets, kann dies ein Problem sein (Grundprojekt ist übrigens eine Vorlage von Uhula)?

Vielleicht hat mein VIS Projekt auch irgendwo einen Fehler, der sich mit dem socket.io Update nicht verträgt, aber ich weiß auch irgendwie nicht mehr wo ich noch suchen könnte. Einzige Lösung derzeit ist bei socket.io 3.1.4 zu bleiben...

Vielleicht helfen Dir diese Infos ja noch irgendwie weiter, Danke schon mal dafür.

**Comment by Apollon77** [comment]
Da sist strange ... muss man mal schauen welche Dependencies sich hier geändert haben weil viel mehr als das war es nicht

**Comment by MK-66** [comment]
Gerade mal mittels Data Counter Widget App geschaut wie beim Handy der Datenverbrauch im heimischen WLAN ohne VPN ist. Gleiches Phänomen: Mit socket.io 3.1.4 werden beim Aufruf der VIS ca. 1MB geladen, mit Version 3.1.5 ca. 18MB. 

Nur fällt im heimischen WLAN das langsame Laden der VIS nicht auf, weil ja nicht erst die vielen Daten über eine ggf. nicht so schnelle Mobilfunk/VPN Verbindung geschaufelt werden müssen. Also irgendwas im socket.io 3.1.5 sorgt bei mir für diesen hohen Datenverbrauch. Gibt es irgendetwas, dass ich noch testen könnte um dem Problem auf die Schliche zu kommen oder Dir damit bei der Suche helfen zu können?

**Comment by MK-66** [comment]
Wollte gerade mal eine komplette ioBroker Neuinstallation auf einer VM machen. Habe dabei festgestellt, dass automatisch socket.io 3.1.5 bei der Installation des web Adapters installiert wird, trotz stable repository.

Könntest Du hier evtl. auch nochmal schauen, dass nur socket.io 3.1.4 bei gewähltem stable installiert wird und nicht trotzdem schon gleich 3.1.5, die ja noch beta ist und bei mir nicht richtig geht.

**Comment by MK-66** [comment]
@ Apollon
Nach einigen Tagen des Probierens mit einer iobroker Test VM, habe ich folgende Erkentnisse:
1.	Ein Downgrade socket.io auf 2.1.2 und web auf 2.4.10 funktioniert: Es werden danach bei der VIS nur 1MB an Daten verbraucht, bei VPN Verbindung nach „Loading values…“ ist meine VIS nach schnellen 2s sichtbar.
2.	Upgrade web auf irgendeine Version 3.x und das Problem ist sofort da: VIS laden verbraucht 18MB Daten, nach „Loading values…“ bzw. im debug log nach „…authenticate“ dauert es bei VPN wieder 12-15s bis meine VIS endlich sichtbar ist.
3.	Socket.io deinstallieren und danach irgendeine web Adapter Version installieren ohne zuvor socket.io neu zu installieren, bringt nach Installation von web trotz stable repo immer die socket.io 3.1.5 hervor, also auch bei Installation einer web 2.x Version. Danach sind das langsame Laden und der hohe Datenverbrauch sofort wieder da.
4.	Ich tippe mal, dass bei Installation des web Adapters immer die socket.io 3.1.5 irgendwie im web Adapter integriert wird und dann irgendwelche lib Daten oder was auch immer geladen werden, die das Problem verursachen.
5.	Zuerst socket.io 3.1.4 installieren und danach eine beliebige web 3.x installieren geht auch nicht, wieder gleiches Problem.
6.	Irgendetwas muss zuvor beim Update der beiden Adapter anders gewesen sein, weshalb ich zuvor in meiner per Snapshot gesicherten Proxmox VM das Problem nicht habe, obwohl dort socket.io 3.1.4 und web 3.4.9 angezeigt werden und der Datenverbrauch hier mit 1MB völlig normal ist und die Ladezeit der VIS die gewohnt schnellen 2s beträgt.
7.	Das Problem wird übrigens erst sichtbar, sobald die VIS etwas größer ist, beim VIS Demoprojekt z.B. fällt das natürlich gar nicht auf.
8.	Ich sprach heute mit einem Arbeitskollegen, der auf meine Empfehlung hin ebenfalls iobroker einsetzt: Er hat genau das gleiche Problem mit dem relativ langsamen Laden seiner VIS und der Datenverbrauch ist beim ihm ca. 8MB (sein Projekt ist derzeit noch etwas kleiner als meins). Er hat immer gedacht, dies läge an seinem langsamen Upload der Fritzbox zu Hause bzw. an seinem Internetvertrag.
9.	Dies könnte u.a. ein Grund sein, warum sich bislang im Forum keiner gemeldet hat. Wenn man weiß, dass das der Aufruf der VIS über VPN mal deutlich schneller war wie in meinem Fall, fällt einem das Problem viel eher auf… Sollte man im Forum evtl. mal nachfragen, ob andere Nutzer ähnliche Probleme haben?
10.	Was wurde denn eigentlich von Euch zuletzt im web bzw. socket.io alles geändert was dieses Problem verursachen könnte und ich vielleicht noch prüfen oder testen könnte?
11.	Wenn Ihr als Entwickler möchtet, könnt Ihr gerne per Teamviewer auf meinen PC schauen, um hier evtl. bestimmte Dateien, meine Installation o.ä. zu checken. Besteht hieran ggf. Interesse? Ich würde mich echt freuen, wenn man eine Lösung finden könnte, schließlich würde ich gerne weiterhin Updates machen, denn iobroker ist wie schon oft gesagt sonst echt toll!

Vielen Dank und ein schönes WE

**Comment by MK-66** [comment]
@Apollon77
Weitere Erkenntnisse mit einer ganz frisch aufgesetzten ioBroker Installation (nur die nötigsten Adapter wie admin, vis, web und socket.io, etc. installiert und mein Projekt importiert):
1.	Jegliche socket.io Version ab V3.x bringt beim Aufruf meiner VIS hohen Datenverbrauch (18MB) und langsame VPN Verbindung

2.	Socket.io Downgrade auf V2.1.2 durchgeführt, Instanz erzeugt und im web Adapter V3.4.9 von integriert auf socketio.0 umgestellt bringt 1MB Datenverbrauch statt 18MB und somit schnelles VPN.

3.	Ich frage mich wie ich bislang jedes Update von socket.io bis hin zu V3.1.4 und web bis V3.4.9 mitmachen konnte, ohne dass dabei der Datenverbrauch beim Aufruf meiner von 1MB auf 18MB gestiegen ist.

4.	Irgendetwas muss doch beim socket.io inzwischen anders geworden sein, was kann das sein, irgendwelche Bibliotheken die geladen werden, andere Abhängigkeiten?

Ich habe auf GitHub beim socket.io gesehen, das V3.1.5 auf stable gezogen werden soll (Issue Bluefox), sollte ich mein Issue aus dem web dort noch zusätzlich verlinken, oder habt Ihr das im Blick?
Es ist echt blöd, wenn so hoher Datenverbrauch beim Aufruf der VIS erzeugt wird (+ langsam). Irgendwann ist da auch mein Mobilfunkvertrag am Ende, zumal es bislang anders war…

Über eine kurze Rückmeldung hierzu würde ich mich freuen.

**Comment by MK-66** [comment]
@Apollon77 
Auch mit JS Controller 3.3.19 und web 3.4.16 gibt es leider noch die gleichen Probleme.

Habt Ihr irgendwelche Erkenntnisse zu dem geschilderten Problem finden können?

**Comment by Apollon77** [comment]
Ich fürchte da muss @GermanBluefox  reinschauen. Welche socket.io version ist bei dir installiert?

**Comment by MK-66** [comment]
@Apollon77 @GermanBluefox 
Derzeit ist bei mir socket,io 3.1.4 installiert. Aber wie auch schon in den Beiträgen zuvor geschrieben wird z.B. inzwischen bei jeder vollständigen iobroker Neuinstallation beim installieren des web adapters trotz stable repo sofort socket.io 3.1.5 mit installiert und ich schätze mal das das das im web integrierte socket.io dann auch irgendwie auch auf der 3.1.5 basiert. 

Also zusammengefasst kann ich sagen, dass bei mir bislang jedes Update von web bis zur V3.4.9 und socket.io bis 3.1.4 problemlos funktioniert hat. Meine Erstinstallation des iobrokers ist ca. aus dem Jahr 2020, bei der die Updates die geschilderten Probleme nicht verursacht haben. 

Irgendetwas muss inzwischen mehr geladen werden, weshalb dieser hohe Datenverbrauch beim Aufruf einer relativ großen Vis entsteht und somit eine Mobilverbindung über VPN so langsam wird.

**Comment by MK-66** [comment]
@Apollon77 @GermanBluefox 
Gibt es Eurerseits schon irgendwelche Erkenntnisse zum geschilderten Problem?

**Comment by MK-66** [comment]
@GermanBluefox @Apollon77 
Gibt es inzwischen irgendwelche Erkenntnisse zum geschilderten Problem?
Ich habe inzwischen ein Update des JS Controllers auf 3.3.22 und Admin 5.2.3 gemacht (Web Adapter 3.4.16) und mit dem neuen Samsung Browser 16.0.2.19 ist plötzlich der Datenverbrauch beim VIS Aufruf wieder bei den gewohnten ca. 1MB. 

Mit Chrome, FF o.ä. bleibt der Datenverbrauch bei den hohen 18MB, ebenso bei der Vorgängerversion des Samsung Internet Browsers 15.0.6.3.

Leider funktioniert mit dem neuen Samsung Browser 16.0.2.19 innerhalb der VIS der Zugriff auf Flot Diagramme nicht mehr. Sobald mehrere Diagramme geladen werden sollen, dreht sich nur der Kreis und der Browser stürzt irgendwann sogar ab. Lädt man innerhalb der VIS nur ein einzelnes Flot Diagramm geht es. Also ist der neue Samsung Browser auch keine Lösung für mich.

Bei Chrome, FF, usw. geht das Laden der Flot Diagramme, aber leider ist man hier wieder bei 18MB Datenverbrauch beim Aufruf der VIS und somit ist eine VPN Verbindung über Mobilfunkt beim Laden extrem langsam.
Irgendetwas stimmt doch da mit den Websockets, socket.io oder was auch immer nicht?

**Comment by mh-hdl** [comment]
...kann das Verhalten der Browser generell bestätigen. Ich nutze die JARVIS-Vis per Fritzbox VPN mit dem Fully Browser auf einem Samsung Android Handy. Im Fully Browser (als auch in Chrome oder Firefox) ist (scheinbar) die zu ladende Datenmenge beim Aufruf der Oberfläche so groß, dass es sehr lange dauert, bis man überhaupt die Startseite sieht. Weiterhin reagieren dann die einzelnen Schaltflächen in JARVIS nur funktionell, aber ohne optisches Feedback, dass z.B. ein roter Schalter grün wird.  Die Änderung ist dann erst nach Reload der Seite (wieder langsam) sichtbar. Mit dem Samsung Internet Browser ist das Problem nicht vorhanden! Leider ist der Samsung Browser keine Alternative, da die Layout Einstellmöglichkeiten nicht so gut sind wie im Fully Browser. Ich dachte erst, es liegt direkt an JARVIS, aber es liegt wohl am Background. Irgendwas macht der Samsung Browser besser / anders.

**Comment by Apollon77** [comment]
Ich glaube wir müssen das mal etwas viel strukturierter angehen. Ich kann es bei mir nicht nachvollziehen.

Frage 1: Was genau heisst "VPN"? VPN über Cloud server? VPN direkt zum iobroker web server? Habe da ein bissl den Überblick verloren weil alles gemischt wird gefühlt.

Frage 2: Kommt das issue von den HTML/JS/CSS Files oder von Daten die per Socketio/Websocket dann nachgeladen werden. AM Web Adapter (und das wäre der erstere Teil) hat sich seit ewig dahingehend nichts geändert. Hier bitte im Browser in die Web Dev Tools unter "Netzwerk" schauen was so geladen wird. macht das sinn? Wie lange dauert das? Gibts da ausreisser?

Frage 3: Kommt man mit downgrades von web und/oder socketio Adapter zu einem Stand wo es tut? Dann muss man versuchen die untershciede zu finden im behaviour. Dazu wäre die Browser Wed-Dev Tools hilfreich weil man dort auch bei den socketio Verbindungen reinschauen kann. Werden die Websockets ständig neu verbinden? Dann könnte es ein Timeout issue sein - sowas gab es bei Admin wenn man zB viele Objekte hat.

Es wäre also super wenn jemand der das Problem hat hier mal tiefer in die Recherche einsteigt und die Infos sammelt!

**Comment by mh-hdl** [comment]
Leider bin ich eigentlich nur ein einfacher User. Detailanalysen kann ich nicht liefern.

Ich auch habe mal ein (Quasi-) Issue im Jarvis- Repo aufgemacht. Vielleicht kann der Programmierer -Zefau- helfen.

https://github.com/Zefau/ioBroker.jarvis/issues/1433#issue-1094061108

zu Frage 1:
Meine VPN-Verbindung ist der faktisch eingebaute Service in Fritz-Boxen. Soweit ich das einschätzen kann, ist es quasi ein Cloud-Service des Herstellers -AVM-. Allgemein gilt wohl dieser Service als nicht besonders schnell, aber das ist auch, glaube ich, nicht das Problem. Die Frage ist ja, warum der Samsung-Browser mit der Verbindung (z.T. auch nur langsam) klar kommt und überhaupt, zügig oder schnell reagiert und faktisch alle anderen, namhaften, scheinbar nicht.

zu Frage 2: 
...kann ich nichts im Detail beitragen. In JARVIS lässt sich die Optik noch durch den User per zusätzliches CSS beeinflussen. Wenn man das aber mal testweise rausnimmt, ändert das nichts.

zu Frage 3: 
Ich habe mal eine Downgrade- Kombination aus Web- 3.4.8 und Socket.io 3.0.13 probiert. Hilft aber auch nichts. Generell ist immer zu spüren, das der Samsung Browser wohl einfach auch der Schnellste (über VPN) ist. Ob es da wirklich diesen besagten 18 zu 1 MB Datenunterschied gibt, kann ich nicht sagen. Das Verhalten war / ist eigentlich immer gleich. Die VPN- Verbindung ist sowieso recht "lahmarschig" (mal besser, mal schlechter, wohl ein AVM/ Fritzbox-Thema), aber die grundsätzliche responsive Bedienung der JARVIS-Oberfläche über VPN geht nur mit dem Samsung Browser, d.h. nur hier "bewegt" sich optisch die Oberfläche. Bei den Anderen schaltet es, aber man sieht es erst nach Seiten-Reload.
Ich gehe erst einmal wieder auf die Latest- Versionen von WEB und Socket.io zurück. Wenn ich gezielt eine Version- Kombi ausprobieren soll, bitte Info.

**Comment by MK-66** [comment]
@Apollon77 
Zu Frage 1: VPN über Fritzbox 7590 Dienst vom Handy ins heimische Netz. Tailscale VPN auf einer Proxmox VM wurde von mir auch schon probiert, gleiches Verhalten. 

Zu Frage 2: Ich hatte aus meinem VIS Projekt schon testweise alle CSS Styles und Skripte entfernt, das ändert am langsamen VPN Ladeverhalten aber nichts.

Das Problem bei einer VPN Verbindung ist möglicherweise gar nicht mal das Datenvolumen (ca. 18MB lt. Data Usage Manager Handy App), sondern dass zwischen der Meldung Authenticate: true (Web Adapter debug Log oder auch bei Chrome DevTools) ca. 8-10s vergehen bevor die VIS dann weiterlädt. Dies passiert bei WLAN nicht.

Über Chrome DevTools mittels USB Debugging vom PC zum Handy bei aktiver VPN Verbindung konnte ich auch im Reiter Network (JS, CSS, WS, etc.) für mich nichts Ungewöhnliches sehen, was diese Zeitverzögerung zwischen Authenticate: true und dem weiteren Laden der VIS verursachen könnte. Es wird in den DevTools zu diesem Zeitpunkt nichts aufgezeichnet oder angezeigt, es vergehen nur einfach 8-10s bevor es in der Console mit Create inner vis object… weitergeht.
Zum Vergleich Finish Meldung DevTools:
Laden VIS über VPN ohne besagtes Web Adapter/socket.io Update: ca. 14s
Laden VIS über VPN mit Web Adapter 3.4.16: ca. 23s

Zu Frage 3: Ich habe bislang alle Updates vom Web Adapter bis V3.4.9 und socket.io bis zur V3.1.4 ohne Probleme mitmachen können (Erstinstallation ioBroker war dabei ca. 2020). Sobald ich nun aber entweder socket.io auf 3.1.5 oder Web auf irgendeine Version nach 3.4.9 update, fängt das Problem an und das Laden der VIS über VPN Verbindung bei Chrome dauert ca. 10s länger. 

Ein Downgrade von Web oder socket.io auf irgendeine 3.x Version hilft nach einem vorherigen Update dann leider auch nicht mehr, das Problem bleibt. Erst ein Downgrade von socket.io auf V2.1.2 (im Web Adapter dabei natürlich von integriert auf socket.io umstellen) funktioniert und bringt den gewohnt geringen Datenverbrauch bzw. die schnellen Ladezeiten zurück. Natürlich gibt es bei socket.io 2.1.2 dann ein paar Warnmeldungen bezüglich des JS-Controllers 3.3.22.

In den DevTools wird im Übrigen sowohl vor als auch nach dem Update des Web Adapters im Reiter Network 8,3MB transferred und 8,3MB resources angezeigt. Der Datenverbrauch auf meiner Handy App wird allerdings anders angezeigt, hier wächst dieser wie gesagt von ca. 1MB auf ca. 18MB.

Ich hoffe, ich konnte es halbwegs verständlich ausdrücken auch wenn Euch dies vermutlich kaum bei der Lösungsfindung hilft.

Danke aber erstmal wieder für Eure Bemühungen.

**Comment by mh-hdl** [comment]
Nachdem ich noch etwas herumgetestet habe und z.B. ein Socktio-Downgrade auf 2.1.2 probiert habe, zeigte sich bei mir keine Verbesserung bzgl. meines VPN-Problems.
Ich habe keine Detail-Ahnung vom Background und kann nicht genau einschätzen, ob die Ursache nun bei Jarvis, im Web-Adapter, im socketio-Adapter oder vielleicht auch im VPN liegt.
Was ich sagen kann ist, dass zumindest der Android-Samsung- Internet-Browser responsiv reagiert und es mit älteren Jarvis-Version (2.x) und wohl (ich kann mich genau erinnern) auch mit einer der 3.x-betas funktionierte...

Letztendlich bin ich mir dann auch nicht sicher, ob ich hier in diesem Issue überhaupt richtig bin? 
Wenn ich mit Info's / Test's doch etwas beitragen kann, lasst es mich wissen.

**Comment by MK-66** [comment]
@mh-hdl 
Also ein VPN Problem kann ich bei mir ausschließen, alle Zugriffe auf das Heimnetz bis auf VIS sind schnell.
Hattest Du eigentlich beim Downgrade von socket.io auf 2.1.2 auch eine Instanz erzeugt (falls nicht vorhanden) und anschließend im Web Adapter ganz unten bei socket.io Instanz von integriert auf socketio (socketio.0) umgestellt?

**Comment by mh-hdl** [comment]
@MK-66 
...ja, die entsprechenden Umschaltungen hatte ich gemacht.

**Comment by mh-hdl** [comment]
...mein Problem ist mit einem Jarvis-Update (3.0.5) beseitigt. Wie vermutet lag es dann wohl doch an Jarvis...

**Comment by MK-66** [comment]
@Apollon77 
Ich habe mir jetzt mit den DevTools auch mal angeschaut, was beim neuen Samsung Browser 16.0.6.23 auf dem Handy passiert, bei dem Flot Diagramme nicht mehr geladen werden, sobald es mehrere Flots auf einer Seite sind:

1. Es kommt schon nach dem Aufruf der VIS Startseite (enthält noch keine Flots) in der DevTools Console folgender Fehler:
`socket.io.js:8 WebSocket connection to 'ws://xxx.xxx.xxx.xx:8082/socket.io/?key=nokey&EIO=3&transport=websocket&sid=ct5Qe-Vynhb_ZpO5AAQO' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`

2. Socketio Verbindungen oder keys werden viele geladen und offenbar auch immer wieder neu (siehe Screenshot)
![DevTools-SamsungBrowser](https://user-images.githubusercontent.com/56516310/148757971-f0104f3c-0e06-4213-97f4-9471f981d1bf.png)

Beim Chrome Browser tritt dies nicht auf, erstens der unter Pkt.1 genannte Fehler nicht und zweitens bleibt es bei nur 3 socketio keys (siehe Screenshot).
![DevTools-ChromeBrowser](https://user-images.githubusercontent.com/56516310/148756575-f2a09028-6958-43c1-9883-76fee7bb37fe.png)

Getestet habe mit einer WLAN-Verbindung vom Handy zur VIS (http). Der Fehler mit dem neuen Samsung Browser tritt im Übrigen sowohl bei meinen in den Posts zuvor genannten „alten“ socketio und Web Adapter Versionen als auch mit den aktuellsten Versionen auf.
Vielleicht hilft Euch diese Info ja zumindest bei der Fehlersuche, warum mehrere Flot Diagramme mit dem neuen Samsung Browser 16.0.6.23 nicht mehr geladen werden können.

Sollte ich noch weiteres testen können, sagt mir bitte Bescheid, Ich danke Euch.

**Comment by Apollon77** [comment]
Ich verstehe nicht warum es nen SSL Fehler gibt bei einer unverschlüsselten Verbindung? Kanns sein das es irgendwelche neuen Sicherheits-EInstellungen im dem Browser gibtda der SSL forciert?? ws: ist unvershclüsselt ... sonst wäre es wss:

**Comment by MK-66** [comment]
@Apollon77 
In den Einstellungen vom Samsung Browser kann ich hierzu nirgendwo etwas finden.

**Comment by MK-66** [comment]
@Apollon77 
Was soll ich sagen, Ihr seid die allerbesten, super Arbeit!!!
Ich habe gerade Updates auf Vis 1.4.8, Web 4.0.0 und socketio 4.0.1 gemacht: Alles ist wieder ok, Datenverbrauch bei meiner VIS (http mit Chrome Browser) ist wieder bei gewohnt kleinen ca. 1MB, somit ist auch die VPN Verbindung über mobiles Netzwerk wieder wie gewohnt schön schnell.

Nur der neue Samsung Browser 16.0.6.23 funktioniert bei der VIS einfach nur noch über https, aber das ist kein ioBroker Problem, sondern einfach der neuen Version des blöden Samsung Browsers geschuldet. Wenn man dann im Web Adapter auf https Verbindung umstellt, ist der Datenverbrauch auch beim Samsung Browser gering und somit schnell.

Von meiner Seite kann das Issue also geschlossen werden.

Tausend Dank an Euch als Entwickler!!!

**Comment by Apollon77** [comment]
Hi, danke für die Rückmeldung. Also war irgendetwas komisches auf socket.io Ebene los ... ich deneke aktiv hat niemand was geändert ;-)) Abern cool das es tut
