### ISSUE TITLE
Fehlermeldung seit Update auf 3.4.9

### ISSUE THREAD

**Issue by Harry423** [ioBroker/ioBroker.web#149]
Seit dem letzten Update auf die Version 3.4.9 bekomme ich folgende Fehlermeldung:

web.0 | 2021-10-28 20:38:42.284 | warn | State "web.0.info.connection" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
web.0 | 2021-10-28 20:38:41.283 | info | ==>Connected system.user.admin from ::ffff:192.168.1.102

In den Objekten gibt es gar keinen "info"-Knoten:
 
![Bildschirmfoto 2021-10-28 um 21 01 05](https://user-images.githubusercontent.com/73777886/139318969-33b16a6f-8af4-4705-80ad-d5dedbd2f615.jpg)

Bis zum Update war das schenibar auch kein Thema?!

**Comment by baennjer** [comment]
Es gibt zwar den Datenpunkt "web.0.connected" aber der Adapter prüft wohl auf "web.0.info.connection" ...

**Comment by Cabohne** [comment]
Das Problem ist bereits in folgendem Issue behandelt, und hat sich wohl mit den neueren Releases erledigt:

#147 

-> müsste nur noch das aktuelle Release 3.4.13 als "stable" freigegeben werden, damit der Adapter einfach aktualisiert werden kann.

**Comment by RP70DP** [comment]
Die 3.4.13 löst das Problem bei mir leider nicht.

**Comment by Apollon77** [comment]
The object is contained in instanceObjects ... so it needs to be created and checked on every adapterstart
