### ISSUE TITLE
web.0 socket.io Cannot detect user

### ISSUE THREAD

**Issue by Farmer-cb** [ioBroker/ioBroker.web#15]
bekomme seit kurzem die Error-Meldung web.0 Socket.io Cannot detect user

weiss nicht ob es an einem Update eines Adapters liegt oder nicht

habe 2 web instancen, 1 x mit https 1 x ohne
in web.0 ist https aktiv und integrierter Socket,
beim aufruf der Webseite kann ich mich anmelden und auch damit arbeiten
welche Daten werden noch benötigt
![web0](https://user-images.githubusercontent.com/38419234/50979179-3e39da80-14f6-11e9-9e59-d1c3f0f294bc.gif)
![socketio](https://user-images.githubusercontent.com/38419234/50979186-41cd6180-14f6-11e9-897e-fe386d147ab6.gif)

`

web.0 | 2019-01-10 16:40:48.440 | error | socket.io Cannot detect user
-- | -- | -- | --
web.0 | 2019-01-10 16:40:38.426 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:40:28.429 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:40:18.428 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:40:08.430 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:40:06.439 | info | ==>Connected system.user.admin from ::ffff:172.16.10.57
web.0 | 2019-01-10 16:39:58.429 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:39:48.430 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:39:38.430 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:39:28.430 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:39:18.432 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:39:08.432 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:38:58.429 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:38:48.430 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:38:38.430 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:38:28.431 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:38:18.429 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:38:08.430 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:37:58.431 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:37:48.430 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:37:38.432 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:37:28.431 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:37:18.431 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:37:08.431 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:36:58.430 | error | socket.io Cannot detect user
web.0 | 2019-01-10 16:36:48.430 | error | socket.io Cannot detect user

`

**Comment by vistalba** [comment]
I run into the same issue but only if I enable one or both of the the two settings:

- authentification
- Socket.IO Instance: internal

**Comment by Apollon77** [comment]
Which version of web? Which js-controller?

**Comment by vistalba** [comment]
@Apollon77 

web server installed version: 2.4.1
socket.io installed version: 2.1.2

**Comment by Apollon77** [comment]
Js Controller you see on Host Tab in admin

**Comment by Apollon77** [comment]
Please install the versions for web and socketio from latest repo please.

**Comment by vistalba** [comment]
@Apollon77 js-controller: 1.5.14

**Comment by Apollon77** [comment]
Still a problem?

**Comment by ma-gu-16** [comment]
Hi, 

das gleiche Problem ist nach Neustart aufgetaucht.

```

web.0 | 2020-11-19 10:03:57.930 | error | (959) socket.io unknown user
-- | -- | -- | --
web.0 | 2020-11-19 10:03:57.889 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:47.914 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:47.906 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:37.911 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:37.884 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:27.891 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:27.883 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:17.905 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:17.898 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:07.922 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:07.892 | error | (959) socket.io unknown user

```

webserver: 3.0.14
scriptenginge: 4.8.4

Level ist auf Debug, keine weiteren Infos... im LOG 

Danke
