### ISSUE TITLE
Log spam (over three thousand times within a two seconds) ==>Connected system.user.admin from ::ffff:192.168.52.25 /  <==Disconnect system.user.admin from ::ffff:192.168.52.25

### ISSUE THREAD

**Issue by CRGer** [ioBroker/ioBroker.web#158]
Web adapter continiously logs "==>Connected system.user.admin from ::ffff:192.168.52.25" and  "<==Disconnect system.user.admin from ::ffff:192.168.52.25"
Just see the attached log...

[log_export.txt](https://github.com/ioBroker/ioBroker.web/files/7534778/log_export.txt)

**Versions:**  
 - Adapter version: 3.4.9
 - JS-Controller version: 3.3.18
 - Node version: v12.22.7
 - Operating system: Raspian

**Comment by Apollon77** [comment]
This log comes when a user connects to the webserver and you see the IP ... so the question is why someone connects several thousand times a second? Find out whats up with this client

**Comment by CRGer** [comment]
I knew where this comes from and it's my desktop PC with one open Tab connected to admin and another to jarvis. The is no reason for thousands of connections. Due to the high amount of logs and maybe something else in the background, my system slowed down and I had to reinstall the web adapter. This solved the issue. Do you want to close that Issue here too? I can't provide any further information.

**Comment by CRGer** [comment]
Hi @Apollon77, please reopen that issue. The bug occurs again, this time from another device (mobile phone). Any idea how to solve this?

**Comment by Apollon77** [comment]
In fact it is no bug... it is "Logging". In fact find out while your devices connect that often ... else increase the loglevel of the instance to "warn" and this "info" log should be gone

**Comment by CRGer** [comment]
Sure, i totally agree. But maybe the high amount of connections, is a bug? Due to the fact the issue occurs with several devices, I don't think that issue is on the device/client side.
