### ISSUE TITLE
State "web.0.info.connection" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by bergjet** [ioBroker/ioBroker.web#168]
raspberry Pi4
js.controller 3.3.21
node.js 14.18.2
web 3.4.9

I have warn: State "web.0.info.connection" has no existing object, this might lead to an error in future versions

**Comment by Apollon77** [comment]
please try "beta" already fixed there, will come to stable soon

**Comment by rmp63526** [comment]
hi, i am using the Version 3.4.16 and still receive this warning! 
For example, when i use vis and switch between the navigationbar it always giv me this warning "State "nothing_selected" has no existing object, this might lead to an error in future versions"

**Comment by gidhap** [comment]
same here, didn't have the warning with previous versions. Updated to 3.4.16 today, now I get 
`<html>
<body>


web.0 | 2022-01-30 13:24:20.411 | warn | State "web.0.info.connection" has no existing object, this might lead to an error in future versions
-- | -- | -- | --



</body>
</html>`
