### ISSUE TITLE
socket fails to update datapoints with "+" in name

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.web#171]
**Describe the bug**  
Example datapoint: 0_userdata.0.Audio+Video.volume
If you change the value, the socket doesn't deliver an update by the stateChange-Event.
Without the "+" in the name of the datapoint it works.

(found in https://forum.iobroker.net/post/726564 )

**Comment by Apollon77** [comment]
@sbormann is this still relevant in current web versions like 5.2?

**Comment by sbormann** [comment]
Hi, thanks for coming back to this. I tested it with the actual version - now it works. Can remain closed.

**Comment by Apollon77** [comment]
Thank you!
