### ISSUE TITLE
Log Warn: Empty pattern on subscribe

### ISSUE THREAD

**Issue by Strobelix80** [ioBroker/ioBroker.web#172]
After opening vis and changing views (by setting some datapoints for view in widget), vis is getting very slow / hanging up for a couple of seconds. 

After a few seconds all changes will be executed immediately one after the other and the log shows:

Web.0 warn Empty pattern on subscribe.

This behaviour repeats every 30-60sec

**Versions:**  
 - Adapter version: :3.4.16
 - JS-Controller version: 3.3.22
 - Node version: 14.18.2
 - Operating system: linux

**Comment by Apollon77** [comment]
When it is caused by vis please open the issue on vis ... or even better: try to find which widget could cause it ... maybe opening it on a widget it even better?
