### ISSUE TITLE
No VIS after update to version 3.4.16

### ISSUE THREAD

**Issue by LPTR72** [ioBroker/ioBroker.web#182]
After updating to 3.4.16 no vis connection is possible.
Update installs soket.io 4.0.3.
After downgrading soket.io to 3.1.5 vis connection works again.

(https://forum.iobroker.net/topic/51964/nach-update-von-web-3-4-16-kein-vis-mehr?_=1643544346942)

**Versions:**  
 - Adapter version: <3.4.16>
 - JS-Controller version: <3.3.22>
 - Node version: <v14.18.3>
 - Operating system: <rpi bullseye>

**Comment by Apollon77** [comment]
web/socketio 4.0 wurde zurückgezogen. Ist mit der 3.x alles ok oder auch probleme? (siehe https://forum.iobroker.net/post/751860)

**Comment by LPTR72** [comment]
Nein, leider nicht alles ok.
Mit dem Update auf 3.4.16 wird Soket IO auf 4.0.3 hochgezogen. 
Nur ein manuelles downgrade auf 3.1.5 hilft einem wieder vis und ECharts zu bekommen. Vorher keine Verbindung möglich.

**Comment by Apollon77** [comment]
>  Mit dem Update auf 3.4.16 wird Soket IO auf 4.0.3 hochgezogen.

passiert das jetzt immer noch? wir haben vorhin die "Latest" versionen auf npm korrigiert, hätte angenommen das das jetzt nicht mehr passiert

**Comment by LPTR72** [comment]
Ich teste morgen noch mal und gebe Rückmeldung. In dem Thread im Forum (Link oben) sind immer noch etliche mit dem Problem.

**Comment by LPTR72** [comment]
Habe die 3.4.16 jetzt doch noch mal auf die Schnelle einfach drüber installiert. Soket.io bleibt auf 3.1.5. Scheint nun also behoben zu sein.

**Comment by Apollon77** [comment]
Danke für die Bestätigung. Also alles ab ca. 20:10 o der so denke sollte sauber sein
