### ISSUE TITLE
Keine Verbindung der Vis nach update von 3.4.9 auf 3.4.16

### ISSUE THREAD

**Issue by tomberlin0** [ioBroker/ioBroker.web#183]
Nach dem update von Version 3.4.9 auf 3.4.16 bekomme ich keine Verbindung mehr auf meine Visualisierung. 
Mein Tablet`s verbinden sich nicht mehr. Bin erstmal wieder auf 3,4,9 zurück.
Was kann das sein?

**Comment by Pnuts76** [comment]
Siehe hier: https://forum.iobroker.net/topic/51964/nach-update-von-web-3-4-16-kein-vis-mehr?_=1643544346942 und hier: https://github.com/ioBroker/ioBroker.web/issues/182
Downgrade von Socket.io zurück auf 3.1.5 sollte helfen.

**Comment by tomberlin0** [comment]
Super, hab`s gerade ausgeführt, läuft. 
Sochet.io zurück auf 3.15 war die Lösung. 
Vielen Dank für die Hilfe.

**Comment by Apollon77** [comment]
DIe verisonen v4 von web und socketip wurden zurückezogen. Also ja, downgrade bitte https://forum.iobroker.net/post/751860
