### ISSUE TITLE
After upgrading to 3.4.16 'not connected' warning triangle shown by each instance.

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.web#184]
**Describe the bug**  
After upgrading to 3.4.16 'not connected' warning triangle shown by each instance.

**To Reproduce**  
Upgrade to 3.4.16 from previous version. Instead of the nice green box, we see warning triangle. See screenshot below.

FYI, previous version was (log from upgrade)... `iobroker Update web from @3.4.9 to @3.4.16`

**Expected behavior**  
Should just work. TBF, does seem to be working so this warning seems bogus and shouldn't be there.

**Screenshots & Logfiles**  

![image](https://user-images.githubusercontent.com/3794098/152008880-326cc878-9533-469f-9ea8-709e68f62058.png)

**Versions:**  
 - Adapter version: 3.4.16
 - JS-Controller version: 3.3.22
 - Node version: v12.22.5
 - Operating system: Raspbian GNU/Linux 11 (bullseye)

**Comment by stenmic** [comment]
I have the same problem but everything works.

**Comment by raintonr** [comment]
> But maybe it is better to not show an error

Absolutely! A web server with no clients is a happy web server, not a web server in error :clown_face:

**Comment by GermanBluefox** [comment]
Fixed in 4.1.3
