### ISSUE TITLE
If URL contains an anchor (#) socket won't connect

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.web#185]
**Describe the bug**  
See subject

In the socket.io.js the handling of anchors in the url needs to be fixed.
For example this way:
In line 82 you could simply remove the anchor-part from window.location.href:
![image](https://user-images.githubusercontent.com/49171332/152153266-2009cf17-d117-447e-9f00-5f02d6ee585e.png)
by using
``window.location.href.replace(/#[^\?]*/, '')``

**Comment by Apollon77** [comment]
Using socketio oder ws?

**Comment by Apollon77** [comment]
Any error in javascritp console?

**Comment by sbormann** [comment]
sorry, i accidently sent the issue before i wrote everything. I updated the issue. Using ws. 
It throws no error, it just doesn't connect. And then setting the socket.on-functions failes:
![image](https://user-images.githubusercontent.com/49171332/152153898-bfbda58b-1568-44aa-b2a0-b9ec586d8bf5.png)

**Comment by sbormann** [comment]
Updated my regex to
``window.location.href.replace(/#[^\?]*/, '')``
