### ISSUE TITLE
Cannot parse "undefined", socket.io [use] unknown user

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.web#189]
Wenn ich iobroker neu starte und in einem Browser zB noch jarvis offen habe, dann bekomme ich jedes mal binnen 1min 1000 Zeilen dieser Art. Erst wenn ich den jarvis Tab reloade, erscheint das iob Login vom web Adapter. Vermutlich versucht jarvis in der Zeit ohne gültige Session weiter die states abzurufen.

> 2022-02-10 08:39:28.707 - warn: web.0 (149100) Cannot parse "undefined"
> 2022-02-10 08:39:28.717 - warn: web.0 (149100) Cannot parse "undefined"
> 2022-02-10 08:39:28.719 - error: web.0 (149100) socket.io [use] unknown user
> 2022-02-10 08:39:28.720 - error: web.0 (149100) socket.io [use] unknown user
> 2022-02-10 08:39:28.819 - warn: web.0 (149100) Cannot parse "undefined"
> 2022-02-10 08:39:28.819 - error: web.0 (149100) socket.io [use] unknown user
> 2022-02-10 08:39:28.923 - warn: web.0 (149100) Cannot parse "undefined"
> 2022-02-10 08:39:28.923 - error: web.0 (149100) socket.io [use] unknown user
> 2022-02-10 08:39:29.055 - warn: web.0 (149100) Cannot parse "undefined"
> 2022-02-10 08:39:29.056 - error: web.0 (149100) socket.io [use] unknown user
> 2022-02-10 08:39:29.064 - warn: web.0 (149100) Cannot parse "undefined"
> 2022-02-10 08:39:29.064 - error: web.0 (149100) socket.io [use] unknown user
> 2022-02-10 08:39:29.226 - warn: web.0 (149100) Cannot parse "undefined"
> 2022-02-10 08:39:29.226 - error: web.0 (149100) socket.io [use] unknown user
> 2022-02-10 08:39:29.270 - warn: web.0 (149100) Cannot parse "undefined"
> 2022-02-10 08:39:29.271 - error: web.0 (149100) socket.io [use] unknown user
> 2022-02-10 08:39:29.374 - warn: web.0 (149100) Cannot parse "undefined"
> 2022-02-10 08:39:29.374 - error: web.0 (149100) socket.io [use] unknown user
> 2022-02-10 08:39:29.401 - warn: web.0 (149100) Cannot parse "undefined"
> 2022-02-10 08:39:29.402 - error: web.0 (149100) socket.io [use] unknown user
> 2022-02-10 08:39:29.509 - warn: web.0 (149100) Cannot parse "undefined"
> 2022-02-10 08:39:29.510 - error: web.0 (149100) socket.io [use] unknown user
> 2022-02-10 08:39:29.595 - warn: web.0 (149100) Cannot parse "undefined"

web 4.1.1 (war aber mit 3.x das selbe)
js-controller 4.0.6 (war aber mit 3.x das selbe)
socket.io 4.1.0 (war aber mit 3.x das selbe)
nodejs 14.19.0

**Comment by Apollon77** [comment]
Also die Session ID die gesendet wird gibt es nicht. Ja das "cannot parse" Fehler mache ich mit JS-Controller 4 weg... aber der rest ist noch so. Der Adapter emittet das Event "reauthenticate" und es scheint so als ob dieses nicht von jarvis beachtet wird. Dafür kann der web Adapter nix :-))

**Comment by Apollon77** [comment]
@GermanBluefox The fact is that the session key exists in the DB BUT contains the string "undefined" ... this means that "undefined" (not as string but as value) was set by someone into that session key ... I tried to find any code that could have done that in socketio but was not able to find any place that could affect that ... Do you have any idea?

In fact yes we can "catch" that case in js-controller, but honestly I would rather like to understand why it happened. ALSO rather then catching it I would more like in js-controller "disallow" to set "Undefined" as a value for the session (maybe same also for null). We could in these cases destroy the session instead or simply decline as "values not allowed". What do you think?

**Comment by Apollon77** [comment]
But @Diginix Jaris shoudl react on "reauthenticate" event

**Comment by GermanBluefox** [comment]
> @GermanBluefox The fact is that the session key exists in the DB BUT contains the string "undefined" ... this means that "undefined" (not as string but as value) was set by someone into that session key ... I tried to find any code that could have done that in socketio but was not able to find any place that could affect that ... Do you have any idea?
> 
> In fact yes we can "catch" that case in js-controller, but honestly I would rather like to understand why it happened. ALSO rather then catching it I would more like in js-controller "disallow" to set "Undefined" as a value for the session (maybe same also for null). We could in these cases destroy the session instead or simply decline as "values not allowed". What do you think?

No one set "undefined" . After the value is expired, the returned value is `undefined` and we try to parse it: https://github.com/ioBroker/ioBroker.js-controller/blob/master/packages/db-states-redis/lib/states/statesInRedisClient.js#L1250

@Diginix It is interesting to know: what do you use? Redis or File/JSONL ?

**Comment by Diginix** [comment]
@GermanBluefox With JS-Controller 4 it was file and now with JS-C 4 it is JSONL. With both I had this issue.

**Comment by Apollon77** [comment]
@GermanBluefox Oooohh yes ... the code will return undefined yes ... in fact it will throw an exception that we ignore ... ok I do something in js-controller

**Comment by Apollon77** [comment]
@Diginix The "Can not parse "undefined" " line will be fixed in js-controller 4.0.8 soon ... rest needs to be fixed in Jarvis by reactng to event said above

**Comment by Diginix** [comment]
Thanks so far!
I'm using jarvis v2, which is unfortunately out of maintenance. I have to take care that no browser tabs are open on no device if I restart iobroker.

**Comment by Apollon77** [comment]
With controller 4 it coukld also work to set loglevel to "warn"

**Comment by Diginix** [comment]
FYI: with js-controller 4.0.8 the "undefined" lines are gone as expected, but as mentioned the "unknown user" lines has to be fixed in jarvis. 
> 2022-02-11 12:21:18.215 - error: web.0 (347853) socket.io [use] unknown user
> 2022-02-11 12:21:18.322 - error: web.0 (347853) socket.io [use] unknown user
> 2022-02-11 12:21:18.667 - error: web.0 (347853) socket.io [use] unknown user

**Comment by Apollon77** [comment]
Thank you for the followup info!
