### ISSUE TITLE
State "web.0.info.connected" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by FlorianGrubert** [ioBroker/ioBroker.web#195]
**Describe the bug**  
The ioBroker.web adapter shows the following warning in the log:
State "web.0.info.connected" has no existing object, this might lead to an error in future versions

The problem alerady exists over a longer time and vrsion history. I thought it should be fixed with Version 3.4.13, but mixed it up with "web.0.info.connectION"

**Versions:**  
 - Adapter version: 3.4.16
 - JS-Controller version: 4.0.19
 - Node version: v14.19.0
 - Operating system: linux on arm

**Comment by Apollon77** [comment]
This is already fixed in the 4.2.0 or even before ...

**Comment by Apollon77** [comment]
PS: WIll come to stable soon
