### ISSUE TITLE
"web.0.info.connected" has no existing object

### ISSUE THREAD

**Issue by klausiob** [ioBroker/ioBroker.web#198]
Logfile shows after update to V3.4.16:
`warn: web.0 (4641) State "web.0.info.connected" has no existing object, this might lead to an error in future versions`

**Versions:**  
 - Adapter version: 3.4.16
 - JS-Controller version: 3.3.22
 - Node version: 14.18.1
 - Operating system: linux auf Raspi

The object structure has no web.0.info.connected. See picture
![webinfoconnected](https://user-images.githubusercontent.com/46675554/158847028-861069c5-0d6d-41a2-99da-9def6994e700.JPG)

**Comment by Apollon77** [comment]
Is fixed in 4.x, already in beta, stable soon
