### ISSUE TITLE
WebSocket connection failed : Invalid frame header

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.web#20]
Ausgangssituation neue installation + web adapter + vis adapter
in verbindung mit eigenen zertifikaten 

web.0 instanz Einstellung 
![grafik](https://user-images.githubusercontent.com/6681528/58975403-2294e080-87c5-11e9-97f6-2be86d0be1f0.png)

jetzt eine neue web instanz dazu 
web.1
![grafik](https://user-images.githubusercontent.com/6681528/58975441-3a6c6480-87c5-11e9-9962-c1d720f6d3b0.png)

die vis öffnen mit der web.0 instanz
![grafik](https://user-images.githubusercontent.com/6681528/58975463-4ce69e00-87c5-11e9-8910-3f2bf989f80b.png)

ab hier geht der web Adapter auf die Bretter mit Fehler
im Chrome
![Unbenannt](https://user-images.githubusercontent.com/6681528/58975481-5e2faa80-87c5-11e9-9b96-18575395cf2e.PNG)

im FF wird die web.0 instanz abgeschossen mit Fehler im Log
![grafik](https://user-images.githubusercontent.com/6681528/58975578-96cf8400-87c5-11e9-8f97-9178edbb0be6.png)

**Comment by GermanBluefox** [comment]
Sind die Zertifikate mit "iob cert create" erzeugt?

**Comment by arteck** [comment]
es ist egal mit welchen zertifikaten es knallt immer

**Comment by arteck** [comment]
> Sind die Zertifikate mit "iob cert create" erzeugt?

ich hab die neuen genommen.. bis jetzt läufts

**Comment by Apollon77** [comment]
Interessant
