### ISSUE TITLE
whitelist does no longer work

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.web#202]
**Describe the bug**  
before the update of "web", "socket.io" und "Web Socket" it was possible to put user on the whitelist of web-adapter. Currently this does no longer work:

**To Reproduce**  
user with own password:
![image](https://user-images.githubusercontent.com/69053781/163853541-fd7d5f76-8ee1-4e29-9c15-16f273bb6f2d.png)
User group authorization
![image](https://user-images.githubusercontent.com/69053781/163853644-3f830f52-cbd0-450a-837c-5c4ed67d2ff7.png)
Instance web:
![image](https://user-images.githubusercontent.com/69053781/163853678-cf3f05b0-30cd-4ee5-a824-0946046a2e87.png)
![image](https://user-images.githubusercontent.com/69053781/163853687-9020bef4-4ae8-4fb8-b581-3643c07bd0d2.png)
Object rights:
![image](https://user-images.githubusercontent.com/69053781/163853717-6ad91f01-7060-4a49-8ed3-582754d29471.png)
Access from the device with IP 192.168.1.160:
![image](https://user-images.githubusercontent.com/69053781/163853755-133834f2-27bf-433f-a56a-2474f916dc04.png)

**Expected behavior**  
Before the update the user was logged in automatically. Currently the vis runtime hangs.

There is also sometime the error `File index.html not found: {}` This can be removed by "playing around with the order of the configuration settings".
The log entry that the device has connected (e.g. `==> Connected system.user.admin from ::ffff:192.168.1.160`) does not appear (anymore) either. So it is stalled somewhere before.

Is there another way to get this to work?

**Versions:**  
WEB-Server: v4.2.3
Web socket: v1.3.0
socket.io: v4.2.0
admin: v5.3.8
Einfache RESTful API: v2.6.4
vis: v1.4.5

same issue also with stable versions:
WEB-Server: v4.2.3
Web socket: v1.2.0
socket.io: v4.2.0
admin: v5.3.8
Einfache RESTful API: v2.6.4
vis: v1.4.5

**Comment by ice987987** [comment]
New user is created (Benutzer 1) and assigned to group `system.group.user`. Benutzer 1 is selected in web-adapter. There is also no access in vis possible. If at "Ausführen als" `admin` Is selected, it works fine:

![C3E2D404-BF5D-4846-BA47-1613ADC3AC9E](https://user-images.githubusercontent.com/69053781/164886651-c016fde4-8caa-4233-be6a-48e6de8baf82.jpeg)
![088B7EA2-B0C4-41B6-8FCB-F1E0F1665459](https://user-images.githubusercontent.com/69053781/164886653-72715c7e-9d32-4416-afd5-7e49091e8858.jpeg)
![0417AD6C-4C43-4AF7-9878-7583D1EEE5F9](https://user-images.githubusercontent.com/69053781/164886655-d58ecdc7-03ff-4a7a-846f-eff47dd106a5.jpeg)

WEB-Server: v4.2.3
Web socket: v1.2.0
socket.io: v4.2.0
admin: v5.3.8
Einfache RESTful API: v2.6.4
vis: v1.4.5

**Comment by ice987987** [comment]
sometimes this error shows up:
`web.0 | 2022-04-26 19:28:57.584 | error | socket.io [use] unknown user`

**Comment by GermanBluefox** [comment]
@ice987987 Does group or user have access to vis/index.html file??
![image](https://user-images.githubusercontent.com/4582016/169642091-0229772f-84ab-4713-9c6a-f335297ea4b6.png)

Or just simple change the vis files owner to your user: 
![image](https://user-images.githubusercontent.com/4582016/169642147-f80556ce-e053-48cc-b865-a26cca886922.png)

**Comment by ice987987** [comment]
I changed the owner now to (this was not the case previosly)
![34F087EF-E01B-4537-BD02-3F51E7D918AC](https://user-images.githubusercontent.com/69053781/169644321-1aad339b-1cd5-47d8-b3c2-8ab9e153fc2e.jpeg)

Instance web:

![](https://user-images.githubusercontent.com/69053781/163853678-cf3f05b0-30cd-4ee5-a824-0946046a2e87.png)
![](https://user-images.githubusercontent.com/69053781/163853687-9020bef4-4ae8-4fb8-b581-3643c07bd0d2.png)

there is now no error but no automatic login from the device with 192.168.1.160

![IMG_3994](https://user-images.githubusercontent.com/69053781/169644539-9c0cbfd0-a6b0-4018-ba86-821626dea0be.PNG)

**Comment by GermanBluefox** [comment]
> there is now no error but no automatic login from the device with 192.168.1.160

Are you sure, that your device does not use IPv6?

**Comment by ice987987** [comment]
Is this screenshot from web v5.1.2? I use web v4.3.0 and there I am not able to add ::ffff:before the IP

**Comment by GermanBluefox** [comment]
> Is this screenshot from web v5.1.2? I use web v4.3.0 and there I am not able to add ::ffff:before the IP

What do you want, I should answer you? :)
