### ISSUE TITLE
	requireLog is not supported by this adapter! Please set common.logTransporter to true

### ISSUE THREAD

**Issue by joergeli** [ioBroker/ioBroker.web#214]
I've just updated web.0 to v5.0.0 from the ioBoker beta-channel.
Now I'm getting warnings like this:
<html><body>

web.0 | 2022-05-19 20:26:38.953 | warn | requireLog is not supported by this adapter! Please set common.logTransporter to true
-- | -- | -- | --

</body>
</html>

Unfortunal many of my VIS-Buttons don't work anymore.
Also in the VIS-Editor I get a popup-Window "Verbindungsfehler".

Any help is welcome.

**Comment by joergeli** [comment]
I have downgraded to **v4.3.0** and everything works fine again.

**Comment by Apollon77** [comment]
Please try web 5.0.1

**Comment by spoeh-man** [comment]
Same on 5.0.1

**Comment by Diginix** [comment]
Same here with web 5.0.1 and Jarvis UI.
Bluefox knows it from forum: https://forum.iobroker.net/post/803924

**Comment by MichaelSchaaf999** [comment]
Same here: v5.1.2

**Comment by mrieglhofer** [comment]
Downgraded to 4.2.3. Then no Log Message and all seems to be working. Downgrade of Websockets had no effekt.

**Comment by Diginix** [comment]
With socketio 6.1.3 and web 5.1.2 I still get these log lines if I hard refresh a browser tab with an already opened jarvis UI.

**Comment by Diginix** [comment]
Issue is still there with web v5.2.0.

**Comment by Harry-58** [comment]
Here the same problem with web v5.2.0.
With every refresh of VIS the error message appears twice in the log

**Comment by GermanBluefox** [comment]
> Here the same problem with web v5.2.0. With every refresh of VIS the warning appears twice in the log

What about the settings? socketio, ws? Integrated, extern? Auth/no Auth? @Diginix , @Harry-58

**Comment by mrieglhofer** [comment]
My updates yesterday

socket.io  4.2.0    6.1.3   
Visualisation  1.4.14    1.4.15   
WEB server  4.2.3    4.3.0 (statt auf 5.1.2 wegen error)
Web socket  1.3.0    2.0.3   

I tried to back with webs ockeres, but no change. Only Webserver 4.3 did the job.

The log error comes when starting webserver. No need for access on my case.

**Comment by Diginix** [comment]
socketio: 6.1.3
ws: 2.1.0
web 5.2.0 (2 instances)

web.0:
![image](https://user-images.githubusercontent.com/39678667/169793843-dcb28216-2f4c-41e9-93bb-efbcb3459533.png)

![image](https://user-images.githubusercontent.com/39678667/169793910-4c1798ea-6eea-4631-a937-0da336695012.png)

web.1
![image](https://user-images.githubusercontent.com/39678667/169794112-8e2fd700-0313-49d1-af04-8dbe55423e4c.png)

**Comment by Harry-58** [comment]
Nur eine Web-Instanz, alles auf einem Raspi 4

![grafik](https://user-images.githubusercontent.com/56926733/169814039-97ca590e-a898-46e1-be2b-d32cdb479fdf.png)


`Meine Adapter:
Adapter    "admin"        : 5.4.9    , installed 5.4.9
Adapter    "cloud"        : 4.1.1    , installed 4.1.1
Adapter    "devices"      : 1.0.10   , installed 1.0.10
Adapter    "discovery"    : 3.0.3    , installed 3.0.3
Adapter    "flot"         : 1.10.7   , installed 1.10.7
Adapter    "frontier_silicon": 0.0.10, installed 0.0.10
Adapter    "history"      : 2.0.1    , installed 2.0.1
Adapter    "hm-rega"      : 3.0.40   , installed 3.0.40
Adapter    "hm-rpc"       : 1.15.12  , installed 1.15.12
Adapter    "icons-mfd-png": 1.1.0    , installed 1.1.0
Adapter    "icons-mfd-svg": 1.1.0    , installed 1.1.0
Adapter    "info"         : 1.9.19   , installed 1.9.19
Adapter    "javascript"   : 5.7.0    , installed 5.7.0
Controller "js-controller": 4.0.23   , installed 4.0.23
Adapter    "mobile"       : 1.0.1    , installed 1.0.1
Adapter    "mqtt"         : 4.0.3    , installed 4.0.3
Adapter    "octoprint"    : 4.0.0    , installed 4.0.0
Adapter    "ping"         : 1.5.3    , installed 1.5.3
Adapter    "rpi2"         : 1.3.2    , installed 1.3.2
Adapter    "sayit"        : 1.12.6   , installed 1.12.6
Adapter    "simple-api"   : 2.6.5    , installed 2.6.5
Adapter    "socketio"     : 6.1.3    , installed 6.1.3
Adapter    "telegram"     : 1.12.6   , installed 1.12.6
Adapter    "text2command" : 2.2.1    , installed 2.2.1
Adapter    "tr-064"       : 4.2.16   , installed 4.2.16
Adapter    "vis"          : 1.4.15   , installed 1.4.15
Adapter    "vis-jqui-mfd" : 1.0.12   , installed 1.0.12
Adapter    "web"          : 5.2.0    , installed 5.2.0
Adapter    "ws"           : 2.1.0    , installed 2.1.0

IOB Info:
Platform       : linux
os             : linux
Architecture   : arm
CPUs           : 4
Speed          : 1500 MHz
Model          : ARMv7 Processor rev 3 (v7l)
RAM            : 3.7 GB
System uptime  : 8d. 20:02:16
Node.js        : v14.19.3
time           : 1653306711220
timeOffset     : -120
adapters count : 499
NPM            : v6.14.17
Disk size      : 14.3 GiB
Disk free      : 4.6 GiB`

**Comment by vepman** [comment]
Bei mir auch ständig:

`(20935) requireLog is not supported by this adapter! Please set common.logTransporter to true`

Versionen:
Admin 5.4.9
socket.io 6.1.3
WEB-Server 5.2.0

**Comment by Harry-58** [comment]
Bei mir kommt die Warning bei allen Views, egal ob mit oder ohne Flot. 
Sogar bei den einfachsten Testviews mit Buttons und Icons.

**Comment by sv-hjo** [comment]
bei mir tritt die Meldung auf, wenn der Kiosk-Browser (App: Fully Kiosk Browser) auf einem Android-Tablet zyklisch neu startet (15 Minuten eingestellt) und sich die Visualisierung über den web-Adapter (HABpanel) neu lädt.

**Comment by Diginix** [comment]
Are there any news regarding this?

**Comment by bob1971** [comment]
https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/logging.md

Edit node_modules\iobroker.socketio\io-package.json and put the line
 "logTransporter": true 
to the common structure, 
since i did this, the warning message had not occured again

**Comment by Diginix** [comment]
@Apollon77 Is this line in io-package.json a proper solution or does this lead to other effects?

**Comment by Apollon77** [comment]
Already thinking about this :-)

**Comment by bob1971** [comment]
17 hours without warning messages and no side effects, maybe it´s not the solution but for me it´s a workaround ;-)

**Comment by GermanBluefox** [comment]
Should be fixed in 5.2.2

**Comment by Brainbug01** [comment]
log entries are gone. works for me.
