### ISSUE TITLE
Initialization of integrated socket.io failed

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.web#215]
after update socket.oi and web ..
![grafik](https://user-images.githubusercontent.com/6681528/169458206-3e06006e-455f-43a2-8d5c-474d816535a2.png)

web does not start with this settings
![grafik](https://user-images.githubusercontent.com/6681528/169458331-79c49890-c529-4b16-817d-760a4a25ab27.png)

**Comment by UweRP** [comment]
Gleiches Verhalten bei mir unter Windows.
`npm install iobroker.web`
hat  keine Veränderung gebracht. Downgrade auf 4.3.0 behebt das Problem.

**Comment by Apollon77** [comment]
geht es mit web 5.0.1?

**Comment by GermanBluefox** [comment]
5.0.2?

**Comment by daniel-lo** [comment]
Hab dies hier auch aktuell 5.1.2 (1~)

<html><body>


web.0 | 2022-05-21 09:11:09.120 | error | {"code":"MODULE_NOT_FOUND","requireStack":["/opt/iobroker/node_modules/iobroker.ws/lib/socket.js","/opt/iobroker/node_modules/iobroker.web/main.js"]}
-- | -- | -- | --
web.0 | 2022-05-21 09:11:09.120 | error | Initialization of integrated socket.io failed. Please reinstall the web adapter.


</body>
</html>

**Comment by GermanBluefox** [comment]
Und ist iobroker.ws installiert?

> Hab dies hier auch aktuell 5.1.2 (1~)
> 
> web.0	2022-05-21 09:11:09.120	error	{"code":"MODULE_NOT_FOUND","requireStack":["/opt/iobroker/node_modules/iobroker.ws/lib/socket.js","/opt/iobroker/node_modules/iobroker.web/main.js"]}
> web.0	2022-05-21 09:11:09.120	error	Initialization of integrated socket.io failed. Please reinstall the web adapter.

**Comment by daniel-lo** [comment]
Äh .. ich hab doch einfach nur Updates gemacht .. dann kam der Fehler.
Zumindest gibt es die Dateien.

**Comment by Nunmalfix** [comment]
Ich habe das gleiche Problem - und mit der 5.1.2 ist auch keine /opt/iobroker/node_modules/iobroker.ws/lib/socket.js Datei vorhanden. Mit 4.3.0 ist sie da.

**Comment by UweRP** [comment]
<html>
<body>


web.1 | 2022-05-21 14:18:01.943 | error | {"code":"MODULE_NOT_FOUND","requireStack":["C:\\Program Files\\iobroker\\iobroker003\\node_modules\\iobroker.ws\\lib\\socket.js","C:\\Program Files\\iobroker\\iobroker003\\node_modules\\iobroker.web\\main.js"]}
-- | -- | -- | --
web.1 | 2022-05-21 14:18:01.942 | error | Initialization of integrated socket.io failed. Please reinstall the web adapter.


</body>
</html>

Auch bei mir der Fehler. WEB socket ist installiert in der Version 2.0.3

**Comment by GermanBluefox** [comment]
Fixed in web 5.2.0

**Comment by daniel-lo** [comment]
confirmed .. thank you!
