### ISSUE TITLE
combobox for socket.io select is buggy

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.web#216]
![grafik](https://user-images.githubusercontent.com/6681528/169458610-82e576e3-dddd-4802-b002-5f2dcdd40665.png)

yes i have 2 instanzes  from ws adapter 
![grafik](https://user-images.githubusercontent.com/6681528/169458676-c62cecdf-3059-4b8b-939c-e021b53e51ec.png)

**Comment by GermanBluefox** [comment]
Fixed in 5.2.0
