### ISSUE TITLE
Caching problem - status code 200 vs. 304

### ISSUE THREAD

**Issue by oke24** [ioBroker/ioBroker.web#218]
Actually I have an issue with permanent loading of 2 svg-files ("fts_window_1w.svg" und "fts_window_1w_open.svg") via the jqui-mfd adapter, associated with the question why these 2 images are always requested in time spans of milliseconds. Per minute I see about 500+ requests for the two svg- files.

Perhaps it is not only a problem with a svg-imagefile from jqui-mfd but something general with caching in the ioBroker web adapter, so I like to crosslink my problem described at 
https://forum.iobroker.net/topic/55247/jqui-mfd-image-request-und-304-problem

The Firefox trace shows requests of the same image 1-6 times a second. First request as expected with a 200 return code.
But then followed by random 304-not modified from the webserver cache as expected answer but also many new 200 return codes, always for the same file. "Last modified" tag isn't set, and ETag doesn't change. As a result the svg-image will in the most requests be reloaded and consumes bandwith and system resources. 

![Bild 263](https://user-images.githubusercontent.com/46261409/170892747-0ef7ca13-555e-40e7-8ced-35f65d8c0fd7.png)

Any help will be appreciated. 

Versions:

Web Adapter version: 5.2.0, Cache active
JS-Controller version: 4.0.23
Node version: v12.22.5
Operating system: Linux

**Comment by Apollon77** [comment]
Can you please click on sucha request and show what cache headers are set? on such a HTTP200 response?

**Comment by oke24** [comment]
yes, very much.

First, HTTP 200 response:

```
Status:
GET
	http://192.168.1.119:8082/vis/widgets/jqui-mfd/img/fts_window_1w.svg
Status
200
OK
VersionHTTP/1.1
Übertragen1,04 KB (1,59 KB Größe)
Referrer Policystrict-origin-when-cross-origin
```

```
Request:
GET /vis/widgets/jqui-mfd/img/fts_window_1w.svg HTTP/1.1
Host: 192.168.1.119:8082
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
Accept: application/xml, text/xml, */*; q=0.01
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://192.168.1.119:8082/vis/index.html?ok
X-Requested-With: XMLHttpRequest
DNT: 1
Connection: keep-alive
```

```
Answer:
HTTP/1.1 200 OK
Content-Type: image/svg+xml; charset=utf-8
ETag: W/"65c-cBjIcQo7zQoRxnzTDVmSymjVZ2o"
Vary: Accept-Encoding
Content-Encoding: gzip
Date: Sun, 29 May 2022 23:23:01 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```

Second, the HTTP 304 response:

```
Status:
GET
	http://192.168.1.119:8082/vis/widgets/jqui-mfd/img/fts_window_1w.svg
Status
304
Not Modified
VersionHTTP/1.1
Übertragen961 B (1,59 KB Größe)
Referrer Policystrict-origin-when-cross-origin
```

```
Request:
GET /vis/widgets/jqui-mfd/img/fts_window_1w.svg HTTP/1.1
Host: 192.168.1.119:8082
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
Accept: application/xml, text/xml, */*; q=0.01
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://192.168.1.119:8082/vis/index.html?ok
X-Requested-With: XMLHttpRequest
DNT: 1
Connection: keep-alive
If-None-Match: W/"65c-cBjIcQo7zQoRxnzTDVmSymjVZ2o"
```

```
Answer:
HTTP/1.1 304 Not Modified
ETag: W/"65c-cBjIcQo7zQoRxnzTDVmSymjVZ2o"
Date: Sun, 29 May 2022 23:23:01 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

**Comment by oke24** [comment]
I kept running the logs in the browser and was able to pinpoint the beginning of the permanent 304 requests.
First (after restarting the web.0 instance) the project VIS page is loaded and then no unexpected request come. 
The following sequence then triggers the phenomenon described above:

```
http://192.168.1.119:8082/socket.io/?key=&EIO=3&transport=polling&t=O4c1FjI --> HTTP 200 OK
http://192.168.1.119:8082/socket.io/?key=&EIO=3&transport=polling&t=O4c1FlF&sid=PnSVQgRPUfkVIePxAABV --> HTTP 200 OK
ws://192.168.1.119:8082/socket.io/?key=&EIO=3&transport=websocket&sid=PnSVQgRPUfkVIePxAABV  --> HTTP 101  Switching Protocols OK
http://192.168.1.119:8082/socket.io/?key=&EIO=3&transport=polling&t=O4c1FpD&sid=PnSVQgRPUfkVIePxAABV --> HTTP 200 
http://192.168.1.119:8082/socket.io/?key=&EIO=3&transport=polling&t=O4c1FpQ&sid=PnSVQgRPUfkVIePxAABV--> HTTP 200 
```

Danach kommen wie beschrieben tausende Requests der Art
`http://192.168.1.119:8082/vis/widgets/jqui-mfd/img/fts_window_1w_open.svg`

Auffällig könnte oben die HTTP Antwort 101 für Switching Protocols sein.

**Comment by Apollon77** [comment]
101 is completely fine. the 304 responses are basically also fine because they mean "unchanged" ... nbut yes we can also add a cahing time for the static assets

**Comment by oke24** [comment]
individual caching time for static assets - that would be a very good enhancement ! Thank you very much.

**Comment by Apollon77** [comment]
why you closed the issue? I reopened

**Comment by oke24** [comment]
my mistake, thx !

**Comment by Apollon77** [comment]
test 5.2.2

**Comment by oke24** [comment]
seems to work well. Initially 2.3 MB are loaded for the start page, then with caching time=300 sec at reload only 40 kB. Status code 200 is returned. The image shows the request of the svg in question.

![Bild 280](https://user-images.githubusercontent.com/46261409/173935672-cc45bbb6-7053-4e51-8bdb-983144b959b2.png)
