### ISSUE TITLE
requireLog is not supported

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.web#226]
![grafik](https://user-images.githubusercontent.com/6681528/172225391-b06c000e-e37a-4d20-adce-856c9ea8006f.png)

![grafik](https://user-images.githubusercontent.com/6681528/172225489-1f2225c4-af4d-4392-8f9c-1d21974d53c2.png)

**Comment by Brainbug01** [comment]
https://github.com/ioBroker/ioBroker.web/issues/214
