### ISSUE TITLE
Overrule system language per ioBroker.web instance

### ISSUE THREAD

**Issue by jpawlowski** [ioBroker/ioBroker.web#228]
While I prefer to keep technical stuff in English, my "end-users" prefer to be addressed in their native tongue.

Currently, there is only a global language setting on the system level. For my end users, I must set this to THEIR language, but I cannot have the internal system run only in English.

It would be great if I could overrule the global language settings for the ioBroker.web adapter so that I could run multiple languages from one ioBroker setup.

The same is obviously true for ioBroker.admin, see https://github.com/ioBroker/ioBroker.admin/issues/1542.

**Comment by Apollon77** [comment]
What exactly you mean? An instance specific language setting foooorrr what?? All UIs via web normally read the system.config object to get the language ... So that would be more a chnage in Aaaaallllll relevant adapters I assume ... @GermanBluefox right?

**Comment by jpawlowski** [comment]
Ok, let's talk personas:

> I as an admin would like to have English as my main language for the IoBroker system. This is so I can use the same language that developers use when developing ioBroker components. To concentrate on admin work, I need to be able to achieve better clarity on different meanings and avoid software bugs related to translation issues, longer strings, different grammar, etc.

and

> I as an end-user would rather see ioBroker presented in my native language, so I feel more comfortable using the system's visual user interfaces. I want to refrain from technical terms and English references that are not part of my native tongue.

Technically I'd consider this actual multi-language support, based on the network port I direct my browser to.
I think that means ioBroker.web needs to forward the language information for each new user session (or every new websocket connection, I suppose).
