### ISSUE TITLE
How to setup the adapter ?

### ISSUE THREAD

**Issue by ggraziotti** [ioBroker/ioBroker.web#24]
I have iobroker on raspberry (ip address 192.168.0.xxx) connect to a router on another lan (192.168.1.xxx).
How to setting up the connection from another exsternal LAN outsite home ?
I have a web domain and static public IP.
How to configure let's encrypt (https)?
Is possible, for test only setting up and http unsecure connection from outside ?

Where Can I find a step by step guide to configure the external access ?

**Comment by Apollon77** [comment]
Double issues are not making sense
