### ISSUE TITLE
SSL-Certificates are no longer selectable

### ISSUE THREAD

**Issue by danieldriessen** [ioBroker/ioBroker.web#240]
### DESCRIPTION:
I added new SSL-Certificates under the system settings.
Those certificates can no longer be selected under the instance settings of the web adapter.
In the admin adapter the newly added certificates work just fine.

I downgraded the web adapter step by step. The problem seems to have first occurred on web adapter version 5.2.0.
After downgrading to web adapter version 5.1.2 my certificates become selectable again under the instance settings of the web adapter and the certificates work just fine.
After that I updated the web adapter again to version 5.2.5. My previously (under version 5.1.2) selected certificates are still set up and still work. However if I open the dropdown menu no selectable certificates are listed again.

### SCREENSHOTS:
_Added certificates under system settings (absolute paths to certificates):_
<img width="1699" alt="Bildschirmfoto 2022-09-03 um 15 05 40" src="https://user-images.githubusercontent.com/6584532/188271831-a4a2d729-8697-476f-97eb-032b506b1a96.png">

_Trying to select added certificates under web adapter version 5.2.5:
(Same situation occurs on all versions down to version 5.2.0)._
<img width="1140" alt="Bildschirmfoto 2022-09-03 um 15 09 47" src="https://user-images.githubusercontent.com/6584532/188271981-0aea986a-b8cc-4817-82c9-401af530fbae.png">

_Trying to select added certificates under web adapter version 5.1.2:_
<img width="1150" alt="Bildschirmfoto 2022-09-03 um 15 12 53" src="https://user-images.githubusercontent.com/6584532/188272054-d375b3cb-03d2-41bc-8e8f-a04eed250851.png">

_Situation after selecting the certificates on web adapter version 5.1.2, saving the changes and re-updating the web adapter to version 5.2.5:
(Previously under version 5.1.2 selected certificates are still stored and working. Changing the selected certificates is not possible since none are listed again under versions > 5.1.2. Currently selected certificate is still working however as long as I don't remove it)._
<img width="1150" alt="Bildschirmfoto 2022-09-03 um 15 16 23" src="https://user-images.githubusercontent.com/6584532/188272209-8d71f2bf-1d98-4488-bb8e-bd54a4e238ce.png">

### Versions:
 - Adapter version: 5.2.5
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: Ubuntu

**Thanks for the help!
(I know I didn't provide logs. If they are needed please just ask). Thanks again!**

**Comment by klein0r** [comment]
Can confirm this with 5.2.7

**Comment by Apollon77** [comment]
@GermanBluefox
