### ISSUE TITLE
[docs] Explain common.webByVersion attribute

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.web#244]
Missing here: https://github.com/ioBroker/ioBroker.web/blob/master/WEB-EXTENSIONS-HOWTO.md

What is the use case?

https://github.com/ioBroker/ioBroker.web/blob/34fd77f847c52c705848c15954fd13d6d30e7f89/main.js#L134-L139

https://github.com/ioBroker/ioBroker.web/blob/34fd77f847c52c705848c15954fd13d6d30e7f89/main.js#L1658-L1665

**Comment by GermanBluefox** [comment]
Look here https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md#adapter for `webByVersion`.
If it is set by the instance, so the prefix will be added to the path with current version to avoid cache of old files. It was used for `material`, but now with new react it is not required anymore
