### ISSUE TITLE
V 5.4.0: Register Haupteinstellungen nicht verfügbar

### ISSUE THREAD

**Issue by ammawel** [ioBroker/ioBroker.web#269]
In der Version 5.4.0. lädt die Registerkarte "Haupteinstellungen" nicht. Das obere blaue Signalband für den Ladevorgang läuft endlos, der Seiteninhalt bleibt weiß ohne Anzeige. 
Register "Extra" wird angezeigt, die anderen Register sind bei mir deaktiviert (wie auch vorher).
Unter V5.3.1 werden die Haupteinstellungen angezeigt.

System: Raspi 4, 8GB, 64 Bit

**Comment by Brainbug01** [comment]
Gleiches Problem hab ich auch.

**Comment by Brainbug01** [comment]
Mit 5.4.1 funktioniert es wieder
