### ISSUE TITLE
web adapter without authentication does not work

### ISSUE THREAD

**Issue by schmupu** [ioBroker/ioBroker.web#27]
I have installed the web adapter in version 2.4.4 and I am configured  two web adapter instances. One with authentication (0.0.0.0:8083) and the other one without authentication (0.0.0.0:8084). 
Since version 2.4.4. the instance without authentication does not work anymore (see screenshots)
The logfile is empty. I am using js-controller 2.0.25. 

configuration:
![Bildschirmfoto 2019-10-11 um 15 38 01](https://user-images.githubusercontent.com/38919572/66655940-4bc6f100-ec3d-11e9-92e9-598fda95e696.png)

Result by calling the web adapter
![Bildschirmfoto 2019-10-11 um 15 38 28](https://user-images.githubusercontent.com/38919572/66655941-4bc6f100-ec3d-11e9-8f65-9613cac334fd.png)

I installed now the version 2.4.0 again. With this version, both instances work.

**Comment by GermanBluefox** [comment]
I cannot reproduce it. Does any one have same issue?

**Comment by schmupu** [comment]
How can I help you? If you like I can install the 2.4.4 again and you can take a look by teamviewer? 
Does it have maybe something to do, that the admin ist password protected, one web instance is password protected too (that works great) and the other one ist not password protetcted?

**Comment by schmupu** [comment]
I figured out, if I try to connect to the web instance which is not protected and which are not working, I am afterwards logged out of the admin.

**Comment by schmupu** [comment]
I think I found the problem. In the web instance configuration the white list is activated for both instances. For the instance web.0 which use the authentication it works great if white lis is activated, but not for instance web.1 which not using the authentication.
Since I disable white list in instance web.1, it works now too. That means I can connect to the VIS, Float, ... without a password in my local network.
I do not know if the "white list" behaevour is an error or not. For what do I need the "white list"?
I will close the Issue, because it works for me now fine.

**Comment by GermanBluefox** [comment]
White list is for automatical authentication from specific IPs
