### ISSUE TITLE
JS Controller 4.0.23 + web 4.3.0 incompatibilities

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.web#270]
I came across the incompatibility discussed here today: https://github.com/ioBroker/ioBroker.js-controller/issues/351

JS Controller 4.0.23, web 4.3.0. These are the latest stable releases AFAIK. If one wants to run 2 web adapters on the same port but different interfaces (ie. one public facing, one private facing) the second to start will fail with '**port _xxxx_ already in use**'.

Looking at the code, it does appear that commit https://github.com/ioBroker/ioBroker.web/commit/b350bed94d1451bc5a1748542ad8c702b36da1dd could have fixed this. Maybe it's time for a new stable release of the web adapter?

**Comment by Apollon77** [comment]
Yes you are completely right ... in fact it is no incompatibility ... it was "just a bug" that was fixed :-) But yes a stable update is planned, but we need to figure out things first in connection to ws and socketip and such

**Comment by mcm1957** [comment]
@Apollon77 
This issue is most likely outdate as js-controller 4.x.x is outdated.
