### ISSUE TITLE
Objekte-Graphik not working due to X-Frame-Options: SAMEORIGIN

### ISSUE THREAD

**Issue by RustyThePropellerHead** [ioBroker/ioBroker.web#29]
Hello,
After performing an update all my modules to the latest versions, I was no longer able to view the graph trends from Flot on the admin web page.

In my browser debug was a fault message: _Refused to display 'http://192....:8082/flot/index.html?range... in a frame because it set 'X-Frame-Options' to 'sameorigin'._, furthermore, clicking on the link in the browsers fault message the graph is displayed.

The background is simple, the iobroker.web is running on port 8081 and the Flot is running on 8082 so the web page is not sourced from the same server, with the option in main.js 'X-Frame-Options SAMEORIGIN being active this is blocking the user from being able to see the graphs.

After commenting out the change made in main.js @ commit [d43dbcdfd622a98c6a820527bfe8238cff51a4d0](https://github.com/ioBroker/ioBroker.web/commit/d43dbcdfd622a98c6a820527bfe8238cff51a) the graphs are working again.

Please evaluate and update.
The same issue is open in the [iobroker.history](https://github.com/ioBroker/ioBroker.history/issues/42) module but does not have to do with that module (in my opinion) 

Cheers,
Rusty

**Comment by GermanBluefox** [comment]
Are you admin running with https?

**Comment by RustyThePropellerHead** [comment]
Nope, also I'm using Google Chrome.

**Comment by Apollon77** [comment]
Is this still relevant in current versions of web?
