### ISSUE TITLE
Feature request: Add long running auth.

### ISSUE THREAD

**Issue by SchumyHao** [ioBroker/ioBroker.web#32]
I have to enter username and password everytime when I want to access web adapters.
I think we can add a option that user can chose to save login info in his device.

This is not same as whitelist. This is give auth to some device.

**Comment by SchumyHao** [comment]
It seems 87acba32535293cd2d4594a743e46e6c6f89480e has add this feature?

**Comment by Apollon77** [comment]
could you verify it? :-)

**Comment by SchumyHao** [comment]
OK

**Comment by SchumyHao** [comment]
Bad news， not working....
What info you need to analysis?

**Comment by Apollon77** [comment]
What exactly is not working? Is cookie set or not?

**Comment by SchumyHao** [comment]
No notice popup when I open 8082 page. And I just enable remember password.
But after some time (one night) I browns 8082 by using same device, I have to enter username and password.

**Comment by Apollon77** [comment]
Please retest with controller 2.2.8. there was an error with Session expiry in controller.
