### ISSUE TITLE
Anmeldung am iobroker.web ab V2.4.8 nicht mehr möglich

### ISSUE THREAD

**Issue by RK62** [ioBroker/ioBroker.web#33]
Nach dem Update von v2.4.6 auf v2.4.8 kann ich mich nicht mehr am iobroker.web anmelden:
- Das betrifft nur web-Instanzen bei denen die Authentifikation aktiviert ist.
- Mit dem User admin (system.user.admin) funktioniert die Anmeldung noch.
- Kennwort im betroffenen User ändern hilft auch nicht.
- Bei neu angelegten User funktioniert die Anmeldung.
Der Änderungseintrag der 2.4.8 (2019-10-16) beschreibt eigentlich das Problem: _(bluefox) Fixed login of non-admin user_, Behebung scheint aber nicht zu greifen.

Ebenso ist mir aufgefallen, dass Hintergrundfarbe und Hintergrundbild nicht mehr angezeigt werden.

Versionen: js-controller: 1.5.14, node.js: V8.16.0, npm: V6.12, web.adapter v2.4.8

Gruß, Ralf

**Comment by RK62** [comment]
Habe herausgefunden woran es liegt:
Die problematischen Accounts sind mit einer ID in G/K-Schreibung angelegt, also **system.user.Test**. Damit scheint es jetzt ein Problem zu geben. 

Abhilfe:
User zum Ändern öffnen, am Namen eine Leerstelle anhängen, wieder raus löschen und speichern. Danach wird der User als **system.user.test** neu gespeichert und funktioniert wieder. 
**Achtung!!!** Überall wo der User verwendet wird, muss er neu angegeben werden (beipielsweise bei den web-Instanzen mit vorgegebenem User "Laufen unter Anwender").

Gruß, Ralf

**Comment by Apollon77** [comment]
welcher js-controller ist im EInsatz?

**Comment by RK62** [comment]
Ich habe das mit js-controller 1.5.14 und 2.1.1 getestet, das Ergebnis ist gleich.

Bei der Anmeldung wird die ID aus dem Benutzer als Loginname genutzt.
- Bei iobroker.web 2.4.6 ist der ID/Loginname scheinbar case-sensitive, daher G/K Schreibung in der ID kein Problem.
- Ab iobroker.web 2.4.10 wird der Loginname bei der Anmeldung scheinbar immer auf Kleinschrift 
geändert, daher ist eine ID mit Großbuchstaben nicht verwendbar.

**Comment by davincino** [comment]
Kann ich bestätigen. Hatte einen User auch extra neu angelegt, um diesen Fehler zu umgehen
