### ISSUE TITLE
JS-Controller 5.0.12: Binary States are deprecated and will be removed in js-controller 5.1

### ISSUE THREAD

**Issue by RP70DP** [ioBroker/ioBroker.web#347]
Adapter: 6.1.2

`2023-09-15 07:19:30.737  - [32minfo[39m: web.0 (1218) Information for Developer: Binary States are deprecated and will be removed in js-controller 5.1, please migrate to Files`

**Comment by Apollon77** [comment]
Can you find out what exactly triggers the error? it is most likely an UI/Visu you use and then zthe issue should be moved there. s ther maybe more log?

**Comment by RP70DP** [comment]
I can try to figure it out.

**Comment by RP70DP** [comment]
Okay, the only VIS-View that triggers the error, is a view with the sonso-widget. I think it corresponds to:

https://github.com/ioBroker/ioBroker.sonos/issues/187

**Comment by Apollon77** [comment]
exactly, so I close here as duplicate
