### ISSUE TITLE
V6.1.5 - no refresh with Minuvis

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.web#353]
since V6.1.5 the Vis with Minuvis don't refresh the page anymore.
( Test: installed js-controller 5.0.13, Node 18.18.1, Minuvis V2.3.3, simple page with switchs in Minuvis.
switch the button/switch in minuvis, you don't see, that it's switched. You have to refresh the complete page manually, than the status of the switch is updated. )
Socketio, WS is not used.

Back to 6.1.4 it works fine as before.
![image](https://github.com/ioBroker/ioBroker.web/assets/36229898/40a97b77-c59a-4c20-b3c4-be3ee9de3e4e)
example page:
![image](https://github.com/ioBroker/ioBroker.web/assets/36229898/c880c5b0-8238-40ed-a457-dd09e686d52d)

if the issue is not depending on iobroker.web, move it to iobroker.minuvis, please.

**Comment by Apollon77** [comment]
any errors in error console?

**Comment by Ilovegym66** [comment]
sure... :-)

![image](https://github.com/ioBroker/ioBroker.web/assets/36229898/df97f001-205b-4bb9-9fcd-1abb7c89d8a7)

**Comment by Apollon77** [comment]
Then amaybe try to ws?

**Comment by Apollon77** [comment]
Dann wäre das jetzt eher erstmal ein minuvis thema. ich habe keine ahnung wie dort die socket Verbindung funktioniert

**Comment by Ilovegym66** [comment]
..denke anders, als es soll.. :-) wir hatten da vor 1-2 Jahren schonmal was... 
kannst du das Issue dahin verschieben oder mach ich ein neues Issue beim Minuvis Adapter und hier zu?

**Comment by guergen1** [comment]
> Dann wäre das jetzt eher erstmal ein minuvis thema. ich habe keine ahnung wie dort die socket Verbindung funktioniert

Mit der normalen VIS geht es aber auch nicht! Erst DG auf 6.1.1 lässt es wieder aktualisieren

**Comment by Apollon77** [comment]
try Web 6.1.5. bitte

**Comment by Ilovegym66** [comment]
Fixed with web v6.1.6 !
Thank you 👍
