### ISSUE TITLE
Problem with included Socket.Io

### ISSUE THREAD

**Issue by thorsten26** [ioBroker/ioBroker.web#37]
I have, like millions of other users the problem that by using Vis on my Meditab M5 with Fully Browser the Vis-View is disconnected always from server if Tablet is going into standby or the Fully-Browser is going to background. Nothing has helped.
When doing screen on or moving Fully Browser to Foreground every time the reload sign from Vis was shown and it takes seconds till the vis view was refreshed - if he was refreshed!! Sometimes the shown data was old - or simply wrong - menas numberfields are showing up as NA.

After days of tests i have found out that the included Socket.io was the problem!

So i installed the socket.io adapter. In my Web.0 Instance in configuration i have chosen to use socketio.0.

Problem gone!

There are still some disconnects after some minutes but by powering screen on immidiatly the connection will be done and all numbers are up to date < 1 second.

Overall the responsetime is much faster then before.

Would be nice to fix that problem.

**Comment by Apollon77** [comment]
This is already availanel in branches and we will update web and socketio very soon. But this is a breaking change because ipad1+2 will no longer work, so we tested carefully
