### ISSUE TITLE
iobroker-App auf Android läd keine Projekte mehr

### ISSUE THREAD

**Issue by Kampfratte** [ioBroker/ioBroker.web#39]
Hallo zusammen

nach Update des iobroker.socketio und iobroker.web auf die 3.0.0 läd die IoBroker-App auf Android keine Projekte mehr und es kommt nur noch "Lade Werte". In der App auf Apple funktioniert alles weiter wie gewohnt. Nur in der App auf Android nicht. Und diese habe ich auf 2 Geräten installiert.
Bin daher wieder bei beiden auf die 2.X.X zurück, denn da funtioniert alles wie gewohnt.

**Comment by Apollon77** [comment]
Was sind es für Geräte? Welche android os ist drauf?

**Comment by Kampfratte** [comment]
Es ist ein Galaxy Tab A mit Android 9 und ein Huaway Media Pad T3 mit Android 7. Auf beiden das selbe Problem. Auf dem iPad funzt es ohne Probleme.

**Comment by thorsten26** [comment]
Ich kann das so nicht bestätigen - Mediapad M5, Android 9.
Allerdings hatte ich auch etliche Probleme mit dem Update was zu einem nicht funktionierendem System geführt hatte - etliche mal wieder Downgrades gemacht. Allerdings kamen auch Updates dazwischen mit Fixes.
Die nun lauffähige Version ist Web 3.0 mit integrierter Socket IO, eine Instanz der socket.io habe ich nicht.

Man muss allerdings auch sagen, das die Iobroker App sehr schwierig ist was Verbindungen angeht, teilweise funktioniert das auch nur wenn man die App komplett neu startet.

Die derzeitigen Einstellungen sind:
SSID Name angeben - Groß/Kleinschreibung beachten!
Socket URL: http://192.168.0.50:8082, kein Kennwort, kein Anwender

**Comment by Apollon77** [comment]
Das issue ist bestätigt. In der App ist die alte Version von socketio drin und die mag mit dem neuen auf Server Seite teilweise nicht. Neue App kommt hoffentlich bald.

**Comment by Kampfratte** [comment]
@thorsten26 ich habe auch den integrierten socket.io benutzt und ich habe auch keine Instanz der Socket.io

Und auch die selben Einstellungen, wie du. SSID angegeben, URL mit Port 8082, kein Kennwort, kein Anwender. Auf dem Huawei läuft es mittlerweile, nur das Re-Sync dauert 10 minuten gefühlt. Auf dem Huawei habe ich Android 7.0. Auf dem Samsung habe ich Android 9 und da geht der Re-Sync beim ersten Teil und dann ist ende. Den 2. Teil (Downloads der Dateien) macht er nicht. Hängt dann über ne halbe Std.

@Apollon77 auf die neue App warte ich schon sehnsüchtig, denn ich musste mit dem web wieder zurück auf die vorige Version, damit ich das Galaxy wenigstens nutzen kann.

**Comment by Apollon77** [comment]
Neue App ist da. Fixed?
