### ISSUE TITLE
Whitelist for vis 

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/ioBroker.web#42]
Hello, everybody,

I have a tablet on the wall. This tablet should be able to log in with a non admin user without logging in to vis. 

Therefore I have entered the fixed IP of the tablet in the white list. Unfortunately this only works for the admin panel. 

Can you check this?

**Comment by Solilord** [comment]
Please consider do do this! Ive got the exact same "problem". For now iam using no athentication at all :/

**Comment by n3roGit** [comment]
At the moment I usw the workaround with a second web adapter only to use whitelist

**Comment by Solilord** [comment]
Ive considered this too
But i cant set the Bind ip Myself :/

**Comment by GermanBluefox** [comment]
Does it works?

> Great I will try it. Is it now possible to use whitelist together with authentication?

**Comment by n3roGit** [comment]
Yes it's working now. You could close it. Thanks!
