### ISSUE TITLE
adapter start unter bestimmten user

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.web#46]
ich kann ur den adapter mit dem Admin user betreiben
![grafik](https://user-images.githubusercontent.com/6681528/82751093-37db9400-9db5-11ea-9157-4e0074daab6c.png)

wechsel ich auf einen anderen mit weniger Rechte läd die Visualisierung nicht

im Log hab ich auch keine Fehler (dev-tools)

**Comment by Apollon77** [comment]
Welche Visualisierung?

**Comment by arteck** [comment]
wie welche Visualisierung.. unsere vis
