### ISSUE TITLE
Options to disable various functions of web adapter

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.web#58]
I notice these URLs are always served by every instance and unlike the authentication interface, CORS, etc. they cannot be disabled:

```
/state/*
*/_socket/info.js
```

Can anything malicious be done with the responses or by sending bogus requests that match these? I don't really know but strikes me there may be a chance this could become a security concern for any public facing instance.

Please either clarify these URLs are safe or add a configuration option to turn off handling of these paths.

**Comment by Apollon77** [comment]
Basically the "info.js" "Just" expose some settings that webpages need to have to use socket.io to connect to the web adapter. This is needed for all the visus to work and should not expose any security relevant data.

The /state/ route allows to access the state values of the system. Here the logged in user or defaultUser permissions are applied.
This is also used by many visus in order to easiely fetch data and also images, js and css files.

What exactly you mean with a "public facing instance"? For sure - as any system in the internet, you need to secure public facing systems as needed. So what exact concerns you have for your use case?

**Comment by raintonr** [comment]
Well, let's say I want a secure web instance that is facing the public internet serving content via HTTPS on port 443. In fact, I have setup such an instance to test a few things.

I want to do this as I have created an adapter which is an extension for the web adapter that responds to various API requests from the public internet (don't worry, secured with OAuth). This is working.

I chose to use an extension of a web adapter rather than having my adapter create it's own ExpressJS app and listen on it's own ports because the web adapter already handles automatic HTTPS certificate generation and such (well - it did once and will again soon I hope).

IMHO it is also architecturally more elegant to have all web serving handled by a single adapter. But of course this means instances of that adapter that face the public internet must be very secure.

As you can imagine, because I have a web adapter instance that is a public facing I want *only* the paths my extension has registered (or those from other extensions, or possibly the login feature, etc. that are *enabled*) to be responded to. I want *everything* else to return a 404 code.

I don't like the sound of what the `/state/` route returns in particular.

What do you think? Could we add a "Run as a hardened server" (or similar) to the instance configuration which would turn off all these responses? Or do you think that is too much of a hassle and I should just change my extension adapter to be a daemon and fire up it's own ExpressJS app?

**Comment by Apollon77** [comment]
Hm ... really honestly I see the webserver more as a "multi purpose internal webservcer that makes sure visus and other web based stuff can be served" and not really as a "hardened" one.
If your API basically should be exposed to the internet then I would never use such a "multi purpase" server, but always  use something which I have strictly under control. So you can do it like simple-api or such and allow the adapter to choose to provide an own HTTP server to service the API (hardened) or use it as web extension (then mainly "Internally focussed")

**Comment by Apollon77** [comment]
PS: the secnd option (but this is only for requests "in" you could use the service options from iobroker.pro server where you can do API calls that end up in states of the cloud adapter

**Comment by raintonr** [comment]
That's fair enough and your answers clarify how the author intended ioBroker.web to be used. Ie. just for internal traffic and never really envisaged for external use.

I can easily create an ExpressJS app inside an adapter so will do that for now.

However, this leads to a further question (which is now off topic for this issue so feel free to move this)...

I note ioBroker.web has settings to expose a letsencrypt challenge server and (when the API is updated - notice it is currently broken) is designed to automatically generate/renew certificates. By it's very nature this challenge server *must* face the public internet. I note there is letsencrypt configuration in the main system configuration and am curious about the connection between code/servers that are run as part of ioBroker.web and how the letsencrypt certificate generation is supposed to work. Specifically, if I create an adapter that requires a certificate for HTTPS traffic did the ioBroker team envisage that something (maybe ioBroker.web) would be used to automatically generate & renew certificates not only for it's own use, but for use by other adapters? I mean, it would make sense that all certificates listed in the system settings/certificates tab are handled when the letsencrypt functionality returns. Was/is that the plan?

**Comment by Apollon77** [comment]
Thats "easy"... When you enable ltes encrypt then an own webserver is opened whe the cert renewal is done - so you specify an extra port and only "forward" this port to the public and that server only runs in the some minutes where it is needed. When I remember correctly it is only thought fir "itself" and not also for others.
But here maybe @GermanBluefox can say more

**Comment by raintonr** [comment]
Now #68 is done... ;)

I think it would be useful to add options to disable various features of a web adapter. Thus, one can have a standard adapter with nothing disabled (works as is) and create a second adapter that can have `/state/*` handling and the rest disabled if required.

Ie. In my installation would have 1 regular adapter (nothing disabled running HTTP internally) and 1 secondary adapter running HTTPS and LE certificates facing the public internet (everything but extensions disabled) and then assign my public extension to this secondary instance.

**Comment by GermanBluefox** [comment]
Thank you @raintonr. We will merge it as the letsencrypt 4 story will be over
