### ISSUE TITLE
error | (959) socket.io unknown user

### ISSUE THREAD

**Issue by ma-gu-16** [ioBroker/ioBroker.web#60]
Hi, 

das Problem ist nach Neustart aufgetaucht.

```

web.0 | 2020-11-19 10:03:57.930 | error | (959) socket.io unknown user
-- | -- | -- | --
web.0 | 2020-11-19 10:03:57.889 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:47.914 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:47.906 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:37.911 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:37.884 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:27.891 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:27.883 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:17.905 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:17.898 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:07.922 | error | (959) socket.io unknown user
web.0 | 2020-11-19 10:03:07.892 | error | (959) socket.io unknown user

```

webserver: 3.0.14
scriptenginge: 4.8.4

Level ist auf Debug, keine weiteren Infos... im LOG 

Danke

**Comment by ma-gu-16** [comment]
Soeben mal den socket.io Adapter isntalliert. keine Besserung :( 
 starting. Version 3.0.13 in /opt/iobroker/node_modules/iobroker.socketio, node: v12.18.2, js-controller: 3.1.

**Comment by ma-gu-16** [comment]
web.0 | 2020-11-19 14:59:17.996 | error | (696) socket.io unknown user
-- | -- | -- | --

Habe Https deaktiviert und der Fehler scheint weg zu sein. Evtl hilft das bei der Problemlösung. 
Hoffe künftig wieder https zu aktivieren können.

**Comment by Apollon77** [comment]
Welche UI rufst DU denn per Web auf wenn der Fehler kommt?

**Comment by ma-gu-16** [comment]
Naja eigentlich keine, ich bin ganz normal im iobroker Backend. 
Wie gesagt, hab jetzt erstmal ohne https. komisch nur das im Grunde das System seit Wochen mit https läuft ohne Fehler. 

Nach dem Reboot war dann der Fehler da. 

Naja denke Ticket kann geschlossen werden. Ich werde SSL die Tage nochmal neu einrichten. Sonst melde ich mich wieder.
