### ISSUE TITLE
When Use "Let's Encrypt certificates" is on, other certificate drop downs should be hidden

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.web#72]
Should hide public, private & chained if Let's Encrypt is on:

![image](https://user-images.githubusercontent.com/3794098/104085702-bbb59400-5251-11eb-9ebd-3657bd915576.png)

**Comment by GermanBluefox** [comment]
In js-controller 2.x these certificates where used as fallback. Now we should check the implementation in 3.3. @Apollon77

**Comment by raintonr** [comment]
I don't think there is any fallback. If LE doesn't work that's a fatal error and it using other certificates is not an option.

**Comment by Apollon77** [comment]
Yes, IF anfallback is used then the "last LE certs" (so pot expired ones)

**Comment by Apollon77** [comment]
But I would maybe not remove the fields but replace the value with kind of an "read only greyed out "Let's Encrypt" or sich or at least add a text why it is gone
