### ISSUE TITLE
Meldung "Connected system.user.admin" kommt sehr häufig im Log

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.web#8]
web.0 | 2018-02-05 20:34:22.424 | info | 2018-02-05T19:34:22.424Z Connected system.user.admin
-- | -- | -- | --
web.0 | 2018-02-05 20:34:21.801 | info | 2018-02-05T19:34:21.801Z Connected system.user.admin
web.0 | 2018-02-05 20:34:21.621 | info | 2018-02-05T19:34:21.621Z Connected system.user.admin
web.0 | 2018-02-05 20:33:41.675 | info | 2018-02-05T19:33:41.675Z Connected system.user.admin
web.0 | 2018-02-05 20:33:41.514 | info | 2018-02-05T19:33:41.514Z Connected system.user.admin
web.0 | 2018-02-05 20:33:41.362 | info | 2018-02-05T19:33:41.362Z Connected system.user.admin
web.0 | 2018-02-05 20:33:03.012 | info | 2018-02-05T19:33:03.012Z Connected system.user.admin
web.0 | 2018-02-05 20:33:02.530 | info | 2018-02-05T19:33:02.530Z Connected system.user.admin
web.0 | 2018-02-05 20:33:01.865 | info | 2018-02-05T19:33:01.865Z Connected system.user.admin
web.0 | 2018-02-05 20:32:21.530 | info | 2018-02-05T19:32:21.530Z Connected system.user.admin
web.0 | 2018-02-05 20:32:21.326 | info | 2018-02-05T19:32:21.326Z Connected system.user.admin
web.0 | 2018-02-05 20:32:21.091 | info | 2018-02-05T19:32:21.091Z Connected system.user.admin
web.0 | 2018-02-05 20:31:41.384 | info | 2018-02-05T19:31:41.384Z Connected system.user.admin
web.0 | 2018-02-05 20:31:41.271 | info | 2018-02-05T19:31:41.271Z Connected system.user.admin
web.0 | 2018-02-05 20:31:41.017 | info | 2018-02-05T19:31:41.017Z Connected system.user.admin
web.0 | 2018-02-05 20:31:03.179 | info | 2018-02-05T19:31:03.179Z Connected system.user.admin
web.0 | 2018-02-05 20:31:02.691 | info | 2018-02-05T19:31:02.690Z Connected system.user.admin
web.0 | 2018-02-05 20:31:01.256 | info | 2018-02-05T19:31:01.256Z Connected system.user.admin

**Comment by GermanBluefox** [comment]
Please check your domestic connection. Because it's you, who is connected and may be from different devices.
