### ISSUE TITLE
Running iobroker on hass os: cant reach web server url

### ISSUE THREAD

**Issue by skank01** [ioBroker/ioBroker.web#81]
**Describe the bug**  
Im running iobroker as addon on hass os.
Whe ntrying to reach the adapter/instance: i get a connection error: cant establish connection

**To Reproduce**  
install iobroker addon on hass os
install web server adapter
try ro launch the url

**Expected behavior**  
i should be able to browse to it

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 3.1.0
 - Operating system: hass os

**Additional context**  
Default port is used 8082

**Comment by Apollon77** [comment]
hass os is docker based, or? if yes you need to enable that port

what is the "iobroker adon for hass os"? this is also unknown to me/us

**Comment by skank01** [comment]
Yes,
It uses docker as a container engine.
Then i need to enable that port, how do i do this?

The iobroker addon is this: https://github.com/MaxWinterstein/homeassistant-addons/

**Comment by Apollon77** [comment]
Then honestly ... maybe ask in that addon repo? ;-)

**Comment by skank01** [comment]
I got it fixed, i had to map the port in iobroker
