### ISSUE TITLE
Extensions interface does not integrate an adapter

### ISSUE THREAD

**Issue by cratoo** [ioBroker/ioBroker.web#86]
After talking to the dev of https://github.com/bropat/ioBroker.eufy-security (@bropat) we found out, that apparently iobroker.web is not loading the webextension of mentioned adapter.

If trying to access a file, that exists in the filesystem of iobroker for this adapter, but would be delivered through the adapter via the web extension I receive an 404, which is coming from iobroker.web and not from the adapter.

For the developer of the adapter the webextension is working, but for me iobroker.web does not even seem to load the extension at all, as the debug log (enabled for both web and eufy-security) does not print the debug statement.

The integration happens as usual in [io-package.json](https://github.com/bropat/ioBroker.eufy-security/blob/master/io-package.json#L248) and should load [web.js](https://github.com/bropat/ioBroker.eufy-security/blob/master/build/lib/web.js).

iobroker.web: 3.2.3
iobroker.admin: 4.2.1
node: v12.18.2

How can I find out, why the extension does not seem to be loaded?

**Comment by Apollon77** [comment]
The relevant stuff for the webExtension should be that like in io-package: https://github.com/bropat/ioBroker.eufy-security/blob/master/io-package.json#L260 , but yes it should load that mentioned file.

Please also checkif your web adapter has disabled the extensions.

ANd please post a log from web adapter starte, best in debug loglevel

**Comment by cratoo** [comment]
Deleting the adapter and the instance, and afterwards reinstalling solved the issue.

**Comment by Apollon77** [comment]
Then most likely an "iobroker upload" was missing
