### ISSUE TITLE
Error 'State "nothing_selected" has no existing object' since update to js-controller 3.2

### ISSUE THREAD

**Issue by eifel-tech** [ioBroker/ioBroker.web#87]
**Describe the bug**  
Using only the "stable" versions of ioBroker and all adapters, web has been working without issues for months now. With the update to js-controller 3.2, it still seem to work all fine but I get recurring warning messages in the log like this:

`web.0 | 2021-02-19 11:51:02.881 | warn | (15841) State "nothing_selected" has no existing object, this might lead to an error in future versions`

**To Reproduce**  
Update as described.

**Versions:**  
 - Adapter version: 3.2.3
 - JS-Controller version: 3.2.16
 - Node version: 12.20.2

**Comment by Apollon77** [comment]
could it be that one of your visus is the originator? normally web adapter is not having that state name at all, so I expect that one visu is "sending" that.

Can you try to find out if this is true?

**Comment by eifel-tech** [comment]
Yes, you're right. On switching a view in vis the warning comes up in log. But I also don't have an element called "nothing_selected" in there. Should the issue be created in [https://github.com/ioBroker/ioBroker.vis](https://github.com/ioBroker/ioBroker.vis) then?

**Comment by Apollon77** [comment]
yes please create in vis! Thank you! (or may it be a widget?) :-)
