### ISSUE TITLE
Many log info entries per second

### ISSUE THREAD

**Issue by dskrt** [ioBroker/ioBroker.web#89]
**Describe the bug**  
Since version 3.3.0 the instance generates many info entries in the logfile

See attached file

**Versions:**  
 - Adapter version: 3.3.0
 - JS-Controller version: 3.2.16
 - Node version: 12.20.2
 - Operating system: ubuntu Server 

![Screenshot_2021-02-26 logs - ioBroker](https://user-images.githubusercontent.com/79701150/109300561-f04bd200-7836-11eb-9fb0-c70a428414a4.png)

**Comment by Apollon77** [comment]
Can you identify that IP/HOst that is listed there? What does that one do?

**Comment by dskrt** [comment]
Hi the IP ist the one of my Macbook, who is connected to VIS, Jarvis and iobroker admin

**Comment by Apollon77** [comment]
COuld it be that somehiow it always reloads the page?

**Comment by dskrt** [comment]
Maybe, that was what I was thinking also, visually I cannot see a reload, seems to me too frequent for a reload, sometimes more then 30-40 messages a second. This behaviour did not exist before....

**Comment by dskrt** [comment]
I took a look into the log of the preceding days: It started when I updated jarvis to 2.2.0 on the 24.2. Closing the jarvis webpage stopped the messages to the log. Now by re-opening the jarvis webpage no more messages are logged. So it looks like jarvis was the problem, I will continue to observe...

**Comment by Apollon77** [comment]
Ok, please open an isue with jarvis adapter then! Please link it to here for reference, thanjk you!
