### ISSUE TITLE
Security Issue: Directory Traversal Attack

### ISSUE THREAD

**Issue by peer69** [ioBroker/ioBroker.web#9]
I am using ioBroker.web current Version 2.1.9 with NodeJS 8.9.4 on Ubuntu Linux and discovered a vulnerability leading to unauthorized access to system files via directory traversal. 
I was able to reproduce the issue by using a simple curl command: 

`curl --path-as-is http://[IOBROKER_IP]:8082/../../../../etc/passwd`

This command would return the systems passwd file, should be working for any file though. As pretty much any file accessible by the user running iobroker (which is root in many cases) could be read using this attack, this might lead to loss of sensitive information as e.g. auth credentials for many adapters are stored in cleartext files in the filesystem.

**Comment by GermanBluefox** [comment]
Are you really sure? Because the web server reads directly only a few files from disk. All other files are read from internal DB. 
And I can't reproduce the error.

**Comment by GermanBluefox** [comment]
Following your logic, the link http://[IOBROKER_IP]:8082/io-package.json should return some text too. But not

**Comment by peer69** [comment]
I validated the issue. There is no io-package.json in the www folder of the adapter, so theres nothing to be returned. 
`curl --path-as-is http://iobroker.home.peer69.de:8082/../../reinstall.sh` works for me, as any other file would. This refers to directory /opt/iobroker by adding two more /.. you can navigate to root and further down the filesystem. 

I created a file 'test' in /opt/iobroker: 
[https://pasteboard.co/H9IC4WX.png](url)

Then I switch to another machine on the same network and try 
`curl --path-as-is http://[IOBROKER_IP]:8082/../../test`
[https://pasteboard.co/H9IDGtA.jpg](url)

This gives me back the file I created to which the webserver should not have access. 

AFAIK I did not change any of the default settings of the adapter: 
[https://pasteboard.co/H9IEiDI.png](url)

**Comment by GermanBluefox** [comment]
@Apollon77 Can you reproduce it?

**Comment by Apollon77** [comment]
@AlCalzone was able to reproduce. Der Telegram

**Comment by AlCalzone** [comment]
As I wrote on telegram, I could reproduce it too.

**Comment by Apollon77** [comment]
I think the trick is really to try it via curl and NOT browser

**Comment by AlCalzone** [comment]
> I think the trick is really to try it via curl and NOT browser

Definitely not in the browser, because that filters out the seemingly unnecessary `../../../`
`curl` also requires the `--path-as-is` option.

**Comment by AlCalzone** [comment]
I think this code branch might be responsible:
https://github.com/ioBroker/ioBroker.web/blob/master/main.js#L749 => https://github.com/ioBroker/ioBroker.web/blob/master/main.js#L817

**Comment by Apollon77** [comment]
Maybe solution is toi "simply" try to normalize the URL before processing ...

One idea is to use Path.normalize and give the path part of the URL :-) if after it is still starts with "../" or such then something is bad because someone tries to do Path Traversal attack :-)

**Comment by AlCalzone** [comment]
> Maybe solution is toi "simply" try to normalize the URL before processing ...

Probably we should sanitize the url itself using built in functions. E.g. by doing this:
```js
var url = require("url");
var safePath = url.parse(url.resolve(host, path)).path;
```
where `host` is some fake host like `"http://localhost"` and `path` is the path to be processed. For our case this results in:
```js
var safePath = url.parse(url.resolve("http://localhost", "../../../../")).path;
// safePath = "/"
```

**Comment by GermanBluefox** [comment]
I really do not understand, who it could be, but can you test the version from github?

**Comment by GermanBluefox** [comment]
May be there is the same issue with simple-api, admin?

**Comment by magenbrot** [comment]
I could reproduce it too with io.web 2.1.9 and curl. Also the github version 2.3.0 of the web adapter has this issue.

Maybe it's an issue with the "express" module from nodejs, as this is the software mentioned in the Response-Header:
`X-Powered-By: Express`

Also a quick scan with openVas shows this security issue. Here's the complete output from openVas:

```
Vulnerability Detection Result
The following traversal URL(s) where found:

Vulnerable url: https://172.16.66.26:8082/../../../../../../etc/passwd

Request:
GET /../../../../../../etc/passwd HTTP/1.1 
Connection: Close 
Host: 172.16.66.26:8082 
Pragma: no-cache 
Cache-Control: no-cache 
User-Agent: Mozilla/5.0 [en] (X11, U; OpenVAS 9.0.2) 
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */* 
Accept-Language: en 
Accept-Charset: iso-8859-1,*,utf-8 
 

Response:
HTTP/1.1 200 OK 
X-Powered-By: Express 
Content-Type: text/javascript; charset=utf-8 
Content-Length: 1862 
ETag: W/"746-fWhY0v9R8VH7fsh4C2eOOtQ3VdA" 
Date: Thu, 12 Apr 2018 11:43:18 GMT 
Connection: close 
 
 
root:x:0:0:Administrator,,,:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
...
```

**Comment by GermanBluefox** [comment]
I could reproduce it on 2.1.9, but cannot on 2.3.0.

Can you please retest one more time? And be sure, that you restarted the instance after update from github.

I used that.
```
const http = require('http');

http.get('http://IPADDRESS:8082/web.0/abc.html', resp => {
    let data = '';
    resp.on('data', chunk => data += chunk);
    resp.on('end', () => console.log(data));

}).on('error', err => console.log(`Error: ${err.message}`));
```

**Comment by magenbrot** [comment]
ok, my fault. sry @GermanBluefox. After restarting the updated instance I'm only getting a file not found error. I thought the instances restart themselfes after updating.

**Comment by Apollon77** [comment]
For normal installs yes. For github installs not :-) so fixed?!

**Comment by GermanBluefox** [comment]
I have additionally the fixes on the js.controller side.
https://github.com/ioBroker/ioBroker.js-controller/commit/8619e5aa51e24e0f2b41a4488275dc0b02f84a80

**Comment by GermanBluefox** [comment]
And thank you for finding it. And it is bit fault. Normally ioBroker should not be in Internet without SSL and Login. But if yes....

**Comment by Apollon77** [comment]
So we can close it?

**Comment by peer69** [comment]
Thanks for addressing the issue! I’d consider it fixed.

**Comment by Apollon77** [comment]
Thank you for reporting from me too
